import { Q } from "./helpers.ts";
import type { Question } from "../types.ts";

export const BOOK: Question[] = [
  Q(
    "b1",
    "book",
    "agentic",
    "In the Agentic Coding crash course, a plan is written during plan mode and the session later dies or is cleared. Which statement matches the course’s reason for also saving that plan as a file such as docs/plans/my-plan.md?",
    [
      "The file survives conversation loss, so a fresh session can be told to read it and continue from a named step.",
      "Neither tool will resume a session unless a plan file exists, so resume and the plan file are one mechanism.",
      "Plan mode refuses to exit until the plan is on disk, which is what makes writing the file mandatory.",
      "The file lets the executing model skip its own reasoning, which is why the course frames it as a speed optimisation.",
    ],
    0,
    "Resume is convenient; a plan file is the durable contract. The course is explicit that the file is a backup if the conversation cannot be resumed, not a speed hack and not a hard requirement of the tools.",
  ),
  Q(
    "b2",
    "book",
    "agentic",
    "A session is still about the same feature, but the transcript is full of dead-end file dumps. Which pair of commands does the course tell you not to confuse?",
    [
      "Both discard the conversation; /compact is the Claude Code spelling and /new the OpenCode spelling of one command.",
      "/compact keeps the same task with less clutter, while /clear or /new wipes the conversation and starts fresh.",
      "/compact summarises and keeps the task, while /clear also reverts the model's file edits across the working tree.",
      "/clear trims the transcript but keeps the rules file loaded, while /compact rebuilds the prompt cache from zero.",
    ],
    1,
    "Concept 6 is the distinction: compact = same task, less clutter; clear/new = start over. Rewind/undo are rollback, not context commands.",
  ),
  Q(
    "b3",
    "book",
    "agentic",
    "OpenCode is started in a repo that already has CLAUDE.md and no AGENTS.md. What does the course say OpenCode will do?",
    [
      "It concatenates CLAUDE.md and AGENTS.md in that order, so both are in context on every message of the session.",
      "It prompts you to rename CLAUDE.md before the first message, since two rules files would otherwise conflict.",
      "It reads CLAUDE.md as a fallback, and if AGENTS.md later appears, AGENTS.md is used and CLAUDE.md is ignored.",
      "It ignores CLAUDE.md entirely, because OpenCode only ever loads a rules file named AGENTS.md from the repo root.",
    ],
    2,
    "OpenCode reads CLAUDE.md when AGENTS.md is absent. If both exist, AGENTS.md is used.",
  ),
  Q(
    "b4",
    "book",
    "sdd",
    "A spec for a password-reset flow names JWT expiry, a Postgres table, and Redis for the token store. What is the Spec-Driven Development course’s primary objection?",
    [
      "Those choices belong in the constitution, which is where durable technical constraints live rather than in one flow's spec.",
      "The spec is sound but incomplete: it should also name the migration that creates the table and the key rotation window.",
      "Password reset sits below the threshold for a spec, so the four-phase loop should be skipped and the flow built directly.",
      "The spec has mixed HOW into WHAT, locking an implementation and failing the test of whether a builder could satisfy it wrongly.",
    ],
    3,
    "Specs are behaviour-only. Implementation choices in the spec freeze the how and make later tool/stack changes a spec rewrite.",
  ),
  Q(
    "b5",
    "book",
    "thesis",
    "The thesis’s 10-80-10 rhythm refers to which split of work?",
    [
      "Roughly 10% human intent, 80% AI execution, and 10% human verification and polish on a piece of work.",
      "Roughly 10% of the workforce human, 80% Digital FTEs, and 10% identic agents acting as personal delegates.",
      "Roughly 10% of the token budget on planning, 80% on execution with cheaper models, and 10% on review passes.",
      "Roughly 10% of companies AI-Native by 2030, 80% hybrid, and 10% untouched by the shift to agent execution.",
    ],
    0,
    "10-80-10 is a rhythm of a piece of work: humans set intent, agents execute, humans verify — not a census of headcount or a token budget.",
  ),
  Q(
    "b6",
    "book",
    "problem",
    "Principle 3 says “looks right” is a failure mode. Which intervention is the principle actually asking for?",
    [
      "A design review of the structure afterwards, because agents accumulate duplication and tangles quickly.",
      "An independent check the agent can run, or that a human can score against a source, a test, or a rubric.",
      "A second pass by a stronger model, since a more capable model is less likely to accept its own output.",
      "Persisting the result to MEMORY.md so later sessions inherit it as verified instead of re-deriving it.",
    ],
    1,
    "Verification is an independent check, not extra eloquence, not memory promotion, and not a freeze in plan mode.",
  ),
  Q(
    "b7",
    "book",
    "openclaw",
    "In OpenClaw’s workspace, which file is the long-term committed-facts layer, as distinct from tone, name/role, and user profile?",
    ["IDENTITY.md", "USER.md", "MEMORY.md", "SOUL.md"],
    2,
    "SOUL = tone, IDENTITY = name/role, USER = who the human is, MEMORY = facts you mean to keep across channels and sessions.",
  ),
  Q(
    "b8",
    "book",
    "layer",
    "The AI Operating Layer course warns against a specific category error: treating which piece as if it were the architecture?",
    [
      "The MCP server list and its connectors",
      "The system of record for knowledge (SoR / KSOR)",
      "The host operating system kernel underneath it",
      "The reasoning model running behind the agent",
    ],
    3,
    "Models are replaceable generators. The durable layer is identity/context, orchestration, governance, harness, capabilities, and trusted records.",
  ),
  Q(
    "b9",
    "book",
    "thesis",
    "The thesis keeps the Agent Factory and the AI-Native company apart. Which pairing matches the text?",
    [
      "The Agent Factory is the spec-driven, human-supervised process; the AI-Native company or agentic enterprise is the output of running it.",
      "They are two names for one thing: a company whose product is whatever its mostly-AI workforce produces under human intent.",
      "The Agent Factory is what an AI-Native company sells, and the AI-Native company is the organisation that buys and operates it.",
      "The Agent Factory is the workforce itself, while the AI-Native company is the governance layer that supervises that workforce.",
    ],
    0,
    "Process versus output is the thesis's first distinction. AI Workers are the workforce the process manufactures.",
  ),
  Q(
    "b10",
    "book",
    "thesis",
    "A deck says “our identic agent is our Digital FTE.” Which correction does the thesis make?",
    [
      "A Digital FTE is an identic agent that has been given a spec, since the spec is the contract between the two layers.",
      "An identic agent is a personal delegate carrying one person's identity and judgment; a Digital FTE is an enterprise role.",
      "An identic agent is the edge tier, and a Digital FTE is the same agent once it has been promoted into a shared channel.",
      "An identic agent handles knowledge work, while a Digital FTE handles only the automation that used to be scripted.",
    ],
    1,
    "The Two-Layer Model separates the Edge (identic) from the AI Workforce (role-based Digital FTEs), with specs as the contract between the layers.",
  ),
  Q(
    "b11",
    "book",
    "agentic",
    "The extension decision tree asks what to reach for when a check “must happen every time, no judgment.” What does the course name?",
    [
      "A skill whose description matches the task",
      "A slash or custom command the human invokes",
      "A hook in Claude Code, or plugin in OpenCode",
      "A plan file the session rereads at each start",
    ],
    2,
    "Every-time, no-judgment enforcement is a hook or plugin. Skills and commands still depend on the model choosing to invoke them.",
  ),
  Q(
    "b12",
    "book",
    "agentic",
    "Which statement about prompt caching matches the course?",
    [
      "Caching applies to the main thread only; subagents run in their own window and never benefit from cached front.",
      "/compact rebuilds the cache from the saved plan file, which is why the course pairs the two in long sessions.",
      "The cache is rebuilt per message, so editing the rules file mid-session costs nothing beyond the tokens added.",
      "A stable front of system prompt, rules and early turns stays cheap, and editing the rules mid-session busts it.",
    ],
    3,
    "The cache rewards a stable prefix. Mid-session rules edits invalidate it, which is one more reason rules files stay short and settled.",
  ),
  Q(
    "b13",
    "book",
    "sdd",
    "One phase of the four-phase workflow has the agent interview the human one question at a time and write no code. Which phase is it?",
    [
      "Clarify — the interview that closes the gaps",
      "Build — the phase where the code is derived",
      "Research — the read-only sweep before writing",
      "Specify — the first written draft of the spec",
    ],
    0,
    "Clarify is the interview: one question at a time, no code, closing the gaps every first spec has.",
  ),
  Q(
    "b14",
    "book",
    "problem",
    "P2 asks you to specify the shape — schema, table, or code — instead of describing it in prose. What is the claimed payoff?",
    [
      "It cuts token use, which the course treats as the main reason to prefer a shape over a paragraph of plain description.",
      "It kills prose ambiguity and buys the five powers: precise thinking, orchestration, memory, compatibility, tool creation.",
      "It lets the agent skip the verification step, because a schema or a table constrains its output better than a test would.",
      "It replaces the system of record for the task, so the agent no longer has to read authoritative state before writing.",
    ],
    1,
    "Code as universal interface is about killing ambiguity in the shape of the thing, and the five powers follow from a machine-readable contract.",
  ),
  Q(
    "b15",
    "book",
    "openclaw",
    "OpenClaw offers three scheduling kinds. Which mapping is correct?",
    [
      "cron for intervals, heartbeat for events, hooks for clock time",
      "cron for retries, heartbeat for webhooks, hooks for approvals",
      "cron for clock time, heartbeat for intervals, hooks for events",
      "cron for events, heartbeat for clock time, hooks for intervals",
    ],
    2,
    "cron is the clock, heartbeat is the interval, hooks are events.",
  ),
  Q(
    "b16",
    "book",
    "layer",
    "The layer course separates ACP, MCP and Skills. Which mapping matches the text?",
    [
      "ACP reaches tools and data, MCP connects agents to hosts, and Skills register capabilities in the layer.",
      "All three connect agents to hosts; they differ only in which operating system family each one targets.",
      "ACP packages procedures, MCP connects agents to hosts, and Skills carry the data contracts between them.",
      "ACP connects agents to hosts such as Xcode, MCP reaches tools and data, and Skills package procedures.",
    ],
    3,
    "Hosts, tools, procedures: ACP reaches the host, MCP reaches tools and data, Skills carry the procedure.",
  ),
];
