import { Q } from "./helpers";
import type { Question } from "../types";

export const BOOK: Question[] = [
  Q(
    "b1",
    "book",
    "agentic",
    "In the Agentic Coding crash course, a plan is written during plan mode and the session later dies or is cleared. Which statement matches the course’s reason for also saving that plan as a file such as docs/plans/my-plan.md?",
    [
      "The file makes the executing model measurably faster because it no longer has to think.",
      "The file survives conversation loss, so a fresh session can be told to read it and continue from a named step.",
      "Neither Claude Code nor OpenCode will resume any session unless a plan file exists.",
      "Both tools refuse to leave plan mode until a plan file has been written.",
    ],
    1,
    "Resume is convenient; a plan file is the durable contract. The course is explicit that the file is a backup if the conversation cannot be resumed, not a speed hack and not a hard requirement of the tools.",
  ),
  Q(
    "b2",
    "book",
    "agentic",
    "A session is still about the same feature, but the transcript is full of dead-end file dumps. Which pair of commands does the course tell you not to confuse?",
    [
      "/compact keeps the same task with less clutter; /clear (or OpenCode /new) wipes the conversation and starts fresh.",
      "/clear summarises the task; /compact deletes the working tree.",
      "/compact and /clear are aliases; both wipe memory and the rules file.",
      "/rewind is the OpenCode name for /compact; /undo is the Claude Code name for /clear.",
    ],
    0,
    "Concept 6 is the distinction: compact = same task, less clutter; clear/new = start over. Rewind/undo are rollback, not context commands.",
  ),
  Q(
    "b3",
    "book",
    "agentic",
    "OpenCode is started in a repo that already has CLAUDE.md and no AGENTS.md. What does the course say OpenCode will do?",
    [
      "Ignore CLAUDE.md until you rename it by hand.",
      "Read CLAUDE.md as a fallback; if both files later exist, AGENTS.md wins and CLAUDE.md is ignored.",
      "Merge both files linewise on every message.",
      "Refuse to start until /init writes AGENTS.md.",
    ],
    1,
    "OpenCode reads CLAUDE.md when AGENTS.md is absent. If both exist, AGENTS.md is used.",
  ),
  Q(
    "b4",
    "book",
    "sdd",
    "A spec for a password-reset flow names JWT expiry, a Postgres table, and Redis for the token store. What is the Spec-Driven Development course’s primary objection?",
    [
      "Those details belong in the constitution, not the spec.",
      "The spec has mixed HOW into WHAT, locking an implementation and failing the test “could a competent builder satisfy this wrongly?”",
      "Password reset is too small for a spec; skip to build.",
      "JWTs are forbidden by the four-phase workflow.",
    ],
    1,
    "Specs are behaviour-only. Implementation choices in the spec freeze the how and make later tool/stack changes a spec rewrite.",
  ),
  Q(
    "b5",
    "book",
    "thesis",
    "The thesis’s 10-80-10 rhythm refers to which split of work?",
    [
      "10% of workers are human, 80% are Digital FTEs, 10% are identic agents.",
      "10% of tokens go to planning models, 80% to cheap models, 10% to reviewers.",
      "About 10% human intent (spec/vision), 80% AI execution, 10% human verification/polish.",
      "10% of companies will be AI-Native by 2030, 80% hybrid, 10% unchanged.",
    ],
    2,
    "10-80-10 is a rhythm of a piece of work: humans set intent, agents execute, humans verify — not a census of headcount or a token budget.",
  ),
  Q(
    "b6",
    "book",
    "problem",
    "Principle 3 says “looks right” is a failure mode. Which intervention is the principle actually asking for?",
    [
      "Ask a stronger model to rewrite the prose until it sounds more confident.",
      "Attach an independent check the agent can run or that a human can score against a source, test, or rubric.",
      "Add the output to MEMORY.md so later sessions treat it as true.",
      "Move the whole task into plan mode so nothing is written.",
    ],
    1,
    "Verification is an independent check, not extra eloquence, not memory promotion, and not a freeze in plan mode.",
  ),
  Q(
    "b7",
    "book",
    "openclaw",
    "In OpenClaw’s workspace, which file is the long-term committed-facts layer, as distinct from tone, name/role, and user profile?",
    [
      "SOUL.md",
      "IDENTITY.md",
      "USER.md",
      "MEMORY.md",
    ],
    3,
    "SOUL = tone, IDENTITY = name/role, USER = who the human is, MEMORY = facts you mean to keep across channels and sessions.",
  ),
  Q(
    "b8",
    "book",
    "layer",
    "The AI Operating Layer course warns against a specific category error: treating which piece as if it were the architecture?",
    [
      "The system of record",
      "The host operating system kernel",
      "The reasoning model (Claude, GPT, Gemini, local)",
      "The MCP server list",
    ],
    2,
    "Models are replaceable generators. The durable layer is identity/context, orchestration, governance, harness, capabilities, and trusted records.",
  ),
];
