import { Q } from "./helpers.ts";
import type { Question } from "../types.ts";

export const BRUTAL: Question[] = [
  Q(
    "x1",
    "brutal",
    "agentic",
    "A practitioner, having observed that an exploratory traversal of a three-hundred-file tree has saturated the primary context window, elects to encode the same traversal as a skill whose description guarantees automatic invocation, on the theory that “skills isolate work.” A colleague objects that isolation of token-heavy reconnaissance is the office of a subagent, whereas a skill merely interpolates a playbook into the already-polluted thread. Which distinction is the course’s?",
    [
      "Both are right in turn: a skill isolates when its description is exact enough, and a subagent isolates when its prompt is narrow enough.",
      "Neither is right: isolation is the office of hooks, which cannot be skipped and therefore cannot leak reconnaissance tokens into the main thread.",
      "The practitioner is right: a skill opens a fresh context window whenever its description matches, so the traversal's reads never touch the main thread.",
      "The colleague is right: a skill interpolates a playbook into the current window, while a subagent reads off-thread and returns only a summary.",
    ],
    3,
    "Skill = playbook in-thread. Subagent = isolated worker returning a summary. Hooks enforce; they do not isolate search.",
  ),
  Q(
    "x2",
    "brutal",
    "sdd",
    "A constitution forbids multi-paragraph comments; a spec, purporting to remain implementation-agnostic, nevertheless stipulates Postgres row-level security and a particular ORM “as acceptance criteria.” A reviewer claims the constitution is the proper home of stack constraints and that the spec has smuggled HOW under the guise of verification. A second reviewer claims acceptance criteria may name any technology if tests will bind it. Which reading is SDD-consistent?",
    [
      "The first reviewer: the spec states observable behaviour, while stack and comment density belong to the constitution and plan; naming an ORM there is a HOW leak.",
      "Neither reviewer: acceptance criteria and the constitution are one artefact under two names, so the objection dissolves once both are versioned together in the repo.",
      "The second reviewer, with a caveat: technologies may appear in the spec provided the Clarify phase has already interviewed the team about each one of them.",
      "The second reviewer: anything a test can bind is observable behaviour, so naming row-level security among the acceptance criteria is legitimate WHAT.",
    ],
    0,
    "Acceptance criteria should make behaviour fail visibly. They should not launder a stack decision into the spec.",
  ),
  Q(
    "x3",
    "brutal",
    "thesis",
    "An executive proposes that an identic agent, because it “carries the founder’s judgment,” should also be the firm’s accounts-payable Digital FTE, thereby collapsing the edge layer and the workforce layer into a single long-lived chat with payment protocols attached. Which thesis objection is the most precise?",
    [
      "Identic agents may not touch the payment protocols at all — ACP, AP2, x402 and MPP are reserved for role-based workers — so the proposal fails before any two-layer argument is reached.",
      "The two-layer model separates a personal delegate at the edge from role-based workers running against a system of record; collapsing them makes the founder's chat an ungoverned ledger.",
      "Digital FTEs cannot be economic actors, since only an identic agent carries the delegated authority needed to hold a signed mandate under AP2 or to settle through an x402 handler.",
      "The objection is procedural rather than architectural: an accounts-payable worker needs an approval card and an audit trail, and neither can be presented from inside a personal chat.",
    ],
    1,
    "Identic ≠ Digital FTE. Payments rails do not license a layer collapse. Records and management still sit under workers.",
  ),
  Q(
    "x4",
    "brutal",
    "problem",
    "A session exhibits simultaneously: (i) a plausible legal memo that misquotes a clause, (ii) a single prompt that rewrote twelve files, and (iii) no execution trace beyond the final paragraph. A consultant maps these, respectively, to Confident Wrong, Big Bang, and Black Box, and assigns P3, P4, and P7. A sceptic says all three are “just context rot” and that /compact is the unique remedy. Which mapping holds?",
    [
      "Neither holds: the Seven Principles govern agents that write code, so a legal memo produced on a desktop surface such as Cowork or OpenWork falls outside their scope entirely.",
      "The sceptic holds: all three are symptoms of one poisoned context, and a single compaction restores the session to a state in which none of them can recur.",
      "The consultant holds: distinct failure patterns answer to distinct principles, and compacting a poisoned chat substitutes for none of citation checks, reversible steps, or a trace.",
      "Both hold in part: the misquotation is properly a P1 failure, because only an artifact produced by the hands — a grep, a diff, a file — can be checked against the source.",
    ],
    2,
    "Do not flatten every failure into context rot. The five patterns are diagnostic, not synonyms.",
  ),
  Q(
    "x5",
    "brutal",
    "openclaw",
    "A public Telegram group is allowed to message an unsandboxed OpenClaw whose workspace includes client secrets and whose MEMORY.md has accreted unvetted “facts” from the channel. A proposer wants a longer SOUL.md instructing the model to ignore injections. A second proposer wants NemoClaw/OpenShell containment, credential hygiene outside the workspace, and a refusal to promote channel text into MEMORY without a human commit. Which is aligned with the course’s threat model?",
    [
      "Neither proposer: what actually stops an injected instruction is quota enforcement, since a 429 response ends the turn before the model can act on anything the channel supplied.",
      "Both proposers together: tone and containment are defence in depth, and a short heartbeat interval statistically dilutes any single injected instruction before it can be acted upon.",
      "The first proposer: a tone file that names the injection patterns is itself a control plane, because the model reads SOUL.md before it ever reads a message from the channel.",
      "The second proposer: a public channel is an injection surface, so cage the filesystem and egress, keep secrets in the credentials store, and treat MEMORY as committed rather than a channel dump.",
    ],
    3,
    "SOUL.md is not a security boundary. Sandbox + secrets discipline + deliberate MEMORY commits are.",
  ),
  Q(
    "x6",
    "brutal",
    "layer",
    "A platform team declares that because they have selected a single frontier model, they now “are” the AI operating layer, and therefore need neither a knowledge system of record nor an audit trail, the model being “self-governing.” Which pair of invariants have they discarded?",
    [
      "Replaceability of the model, and governance with trusted records",
      "The first two principles of the problem-solving course, P1 and P2",
      "Plan mode and /compact, the two disciplines of context",
      "The agent authorization and payment rails — ACP, AP2, x402 and MPP",
    ],
    0,
    "The layer’s point is that the model is a slot. Records and governance outlive it. Self-governing models are the category error the course names.",
  ),
  Q(
    "x7",
    "brutal",
    "agentic",
    "An engineer, citing Uncle Bob’s 2026 remark that he no longer reads agent-written code, disables all review and ships on a single green test file the agent also authored. Cherny’s verification claim and Martin’s actual sequence are being used as a permission slip. What ratio does the course insist on?",
    [
      "Celebrity practice is evidence enough: if an engineer of that standing no longer reads diffs, a single green test file authored by the agent is a sufficient checker.",
      "Trust is proportional to the checkers you can name: Martin built the constraints first, and Cherny's 2–3× claim assumes a check the model cannot skip.",
      "Hooks become unnecessary once review is removed, because the commit path no longer has a human reader to satisfy and the test file becomes the whole gate.",
      "The sequence is being read backwards: verification follows delivery on the agentic ladder, so shipping on one green file and checking later is the intended order.",
    ],
    1,
    "The course is explicit: he built the checks first. Confidence is the size of the checkers, not a mood and not a tweet.",
  ),
  Q(
    "x8",
    "brutal",
    "thesis",
    "Granted that the identic agent is described as the locus of a single person's identity, judgment and delegated authority, and granted that Digital FTEs are described as role-bearing members of an AI workforce, which reading of the Two-Layer Model does the thesis actually support?",
    [
      "The model is about model size: the Edge runs small local models while the workforce runs frontier ones, and nothing else separates the two.",
      "The layers are deployment tiers, so an identic agent that has been promoted into a shared channel has thereby become a Digital FTE.",
      "The Edge and the AI Workforce are distinct layers whose contract is the spec; reuse does not make a personal delegate an enterprise role.",
      "The model implies that Digital FTEs subsume identic agents once governance is added, since governance is what the edge layer is said to lack.",
    ],
    2,
    "The two layers are separated by responsibility, not by hosting. Specs are the contract between a person's delegate and the role-based workforce.",
  ),
  Q(
    "x9",
    "brutal",
    "agentic",
    "Although both commands reduce what the model is carrying, and although the transcript still exists in both cases immediately afterwards, the course treats /compact and /clear (or OpenCode /new) as non-interchangeable. On what distinction does that insistence rest?",
    [
      "/compact reverts the model's file edits across the working tree, whereas /clear only trims the transcript that the model carries.",
      "The distinction is tool-specific rather than conceptual: Claude Code ships both commands and OpenCode ships neither of them.",
      "Only /clear invalidates the prompt cache, which is why the course reserves it for the moment a session has become expensive.",
      "/compact preserves the current task with less clutter, whereas /clear or /new abandons the conversation and starts fresh.",
    ],
    3,
    "Same task with less clutter versus a clean start. Treating them as aliases is how people wipe a task they meant to keep or keep a thread they meant to kill.",
  ),
  Q(
    "x10",
    "brutal",
    "agentic",
    "A team argues that a skill with an exacting description and a hook on the commit path are equivalent guarantees, since neither can be forgotten by a human. Which characterisation of the difference survives the course's account?",
    [
      "The skill is expertise the model may elect to apply when the task matches; the hook fires whatever the model decides, which is what suits absolutes.",
      "The hook is the cheaper of the two mechanisms, so it should be preferred wherever both would work, with the skill reserved for genuine judgment calls.",
      "The skill runs in an isolated context of its own while the hook runs in the main thread, which is the only difference that matters for token cost.",
      "They are equivalent guarantees: both are configuration the model reads before it acts, and neither depends on a human remembering to invoke it.",
    ],
    0,
    "Election versus enforcement. A skill is a playbook the model can consult; a hook is a check the model cannot talk its way around.",
  ),
  Q(
    "x11",
    "brutal",
    "sdd",
    "It is sometimes proposed that, because the constitution carries the durable principles, constraints and done criteria of a project, it can be relied upon to prevent the failures it names. Which qualification does the course attach to that proposal?",
    [
      "None: a constitution binds the way a compiler binds, and a line that has been written down cannot subsequently be ignored by the model.",
      "The constitution is not self-enforcing: absolutes need tests or hooks, and each line must earn its place against “if I remove this, will a mistake happen?”",
      "The constitution is unenforceable in principle, which is why the course prefers to keep durable constraints inside the spec where acceptance criteria bind them.",
      "The constitution binds only during the Clarify phase, when no code is being written and the interview is still open; afterwards the spec governs alone.",
    ],
    1,
    "Principles on a page are not a control. Where a mistake is unacceptable, the check has to run without anyone remembering it.",
  ),
  Q(
    "x12",
    "brutal",
    "problem",
    "An agent's transcript is fully visible, each step logged, and the human can follow every decision; the output is nonetheless wrong, and nothing in the transcript would have revealed that. Which principle was satisfied, and which was not?",
    [
      "Neither was satisfied: a transcript records what was said rather than what was done, so it is not the execution trace P7 asks for either.",
      "Both were satisfied, and the failure belongs to P4: the task was too large to be reversible, which is why the wrongness went unnoticed.",
      "P7 was satisfied and P3 was not: seeing every step the agent took is not the same thing as an independent check that the result is correct.",
      "P3 was satisfied and P7 was not, because a log of decisions is not observability in the sense the principle requires of a directed system.",
    ],
    2,
    "Observability tells you what happened. Verification is an independent check — tests, rubric, quote-the-source, cross-model review — and confident wrongness is its failure pattern.",
  ),
  Q(
    "x13",
    "brutal",
    "openclaw",
    "A connector has been added, the gateway reports no error, and the capability it was added for never appears in the assistant's behaviour. Which diagnostic ordering does the course recommend before anything is reinstalled?",
    [
      "Edit SOUL.md so the assistant is told explicitly about the new tool, then /reset, since brain files are read before any connector is invoked.",
      "Replace the skill with an MCP tool of the same name, because a skill that does not fire is always a description problem rather than a wiring one.",
      "Reinstall OpenClaw and re-run onboarding with --install-daemon, since a connector that reports no error and does nothing is a broken install.",
      "Read the gateway log, because MCP tools can fail silently, and only then change configuration; a skill that never fires is a different fault.",
    ],
    3,
    "Silent MCP failure is a named pitfall and the gateway log is the named source of truth. Skills and MCP tools are different mechanisms with different failure modes.",
  ),
  Q(
    "x14",
    "brutal",
    "layer",
    "The stack places the reasoning model below the agent and the harness, and describes the harness as a control plane rather than a compute or sandbox plane. Which inference does that placement license?",
    [
      "That the model can be swapped without redoing identity and context, orchestration, governance, capabilities or trusted records.",
      "That the harness executes whatever the model declines to do, which is why it sits above the agent rather than beside it in the stack.",
      "That the model is the architecture after all, since everything drawn beneath it in the stack is plumbing that the model may ignore.",
      "That governance becomes optional once the harness enforces approvals, because the control plane has then absorbed the audit trail.",
    ],
    0,
    "Replaceability is the point of the separation: model is not agent is not layer. Treating the model as the architecture is the category error the course names.",
  ),
];
