import { Q } from "./helpers";
import type { Question } from "../types";

export const SOLO_A: Question[] = [
  Q(
    "s1",
    "solo",
    "agentic",
    "You notice the model is sorry, looping on the same patch, naming files that do not exist, and contradicting a constraint from earlier in the same thread. You still need the feature. What is the first action the course wants, before any new design talk?",
    [
      "Explain the contradiction again, quoting your old message, so the model can align.",
      "Stop. Compact or clear. Do not try to repair a poisoned window with another prompt.",
      "Add four new rules covering each symptom, then continue.",
      "Disable permissions so the model can “just finish.”",
    ],
    1,
    "The diagnostic is explicit: stop typing; compact or clear; do not fix poison with more tokens.",
  ),
  Q(
    "s2",
    "solo",
    "agentic",
    "You want something that cannot be skipped: block git commit if lint or tests fail. You already have a paragraph in AGENTS.md that says the same thing, and the model still commits red. Which mechanism is missing?",
    [
      "A longer paragraph, placed at the top of AGENTS.md.",
      "A skill whose description mentions lint.",
      "A hook/plugin on commit that returns the failure to the model as the next instruction.",
      "MCP to GitHub so commits happen off-machine.",
    ],
    2,
    "The verification loop is hook/plugin plus a check the model cannot decline.",
  ),
  Q(
    "s3",
    "solo",
    "agentic",
    "You keep typing the same “how we write API routes” briefing. It is not a hard gate, but you want it applied when that work comes up, without paying for it on unrelated turns. Where does it go?",
    [
      "The rules file, because all writing advice is a critical rule.",
      "A skill, auto-invoked from its description, running in the current window.",
      "A subagent, because all expertise must be isolated.",
      "A cron heartbeat in OpenClaw.",
    ],
    1,
    "Decision tree: auto expertise on match → skill. Subagent is for isolating heavy work, not for a playbook.",
  ),
  Q(
    "s4",
    "solo",
    "agentic",
    "You ask the main session to “find where we compute tax and dump everything you open.” Later the model forgets the plan you approved. Which concept did you violate first?",
    [
      "Permissions discipline",
      "Match the model to the task",
      "Subagents / context engineering: heavy reads belong off-thread",
      "MCP honesty",
    ],
    2,
    "Search dumps are the classic way to poison the main window.",
  ),
  Q(
    "s5",
    "solo",
    "agentic",
    "You edited CLAUDE.md in the middle of a long session and the next message suddenly costs far more. The course’s cache note says what?",
    [
      "Rules files are never cached, so this is unrelated.",
      "The discount holds only while the front of the context is stable; editing the rules file resets that front.",
      "You must run /compact twice to rebuild the cache.",
      "OpenCode cannot cache; only Claude Code can.",
    ],
    1,
    "Prompt caching is a provider feature keyed on a stable prefix. Rules edits bust it.",
  ),
  Q(
    "s6",
    "solo",
    "agentic",
    "Claude Code undoes a bad edit with Esc Esc. A file the agent deleted via a shell command does not come back. Is that a bug relative to the course?",
    [
      "Yes; Claude Code undo always includes bash.",
      "No; Claude Code checkpointing covers the model’s file edits, not shell side-effects. OpenCode’s git-backed /undo is broader.",
      "No; nothing in either tool can undo anything.",
      "Yes; you forgot /redo.",
    ],
    1,
    "The course flags this exact difference. Git remains the real history.",
  ),
  Q(
    "s7",
    "solo",
    "agentic",
    "You auto-approved every bash on day one, including rm and git push, because watching permissions felt slow. Which arc does the course describe instead?",
    [
      "Start fully open; tighten after the first incident.",
      "Start with ask-on-every-action; auto-allow only actions that earned trust; keep a deny list for destructive commands.",
      "Permissions are deprecated once plan mode exists.",
      "Only OpenCode needs permissions; Claude Code is sandboxed by default for all bash.",
    ],
    1,
    "Trust is earned session by session. Deny lists stay for rm -rf, publish, push.",
  ),
  Q(
    "s8",
    "solo",
    "agentic",
    "A stealth “free” model appears in /models under a codename. You are about to point it at a client repo. What two cautions does the course stack?",
    [
      "They are always stronger than billed models, and they never train on prompts.",
      "They are temporary/unannounced, and “free” may mean your prompts and code are the payment — not for confidential work.",
      "They only work in plan mode.",
      "They require MCP.",
    ],
    1,
    "Stealth models can vanish and may use your data. Use them for throwaway experiments.",
  ),
  Q(
    "s9",
    "solo",
    "agentic",
    "You are about to paste a full test run into the chat so the model can “see the failures.” The course’s cost/context habit is?",
    [
      "Paste everything; caching makes it free after the first time.",
      "Write the output to a file and report one line (path, count, where). The file is idle until searched.",
      "Always switch models before pasting logs.",
      "Put the log in CLAUDE.md so it is always present.",
    ],
    1,
    "Huge tool output in the transcript is paid again on every later turn and poisons attention.",
  ),
  Q(
    "s10",
    "solo",
    "agentic",
    "You want a second opinion on a diff. The same model that wrote the code is cheapest to use as reviewer. What does Part 8 claim?",
    [
      "The writer is the best reviewer because it has full memory of intent.",
      "The writer shares the blind spots that caused the mistakes; a different model (ideally a different provider) catches different classes of error.",
      "Review is only valid if done by a human.",
      "Review must happen in the same conversation to keep cache hits.",
    ],
    1,
    "Cross-model review is the point of mixing providers. Same-model review still beats none, but it is weaker.",
  ),
  Q(
    "s11",
    "solo",
    "agentic",
    "You run five sessions on the same branch and they fight over files. The isolation pattern in the two-tools chapter is?",
    [
      "Disable permissions.",
      "Git worktrees (or equivalent isolated checkouts) so sessions do not share a dirty tree.",
      "One global CLAUDE.md per user, not per project.",
      "Always use stealth models for parallel work.",
    ],
    1,
    "Parallelize only with isolation. Cherny’s own workflow is multiple checkouts.",
  ),
  Q(
    "s12",
    "solo",
    "sdd",
    "Your “spec” is a list of files to create and a chosen ORM. Build succeeds and still misses a business rule that was only in a Slack paragraph. What was the spec missing, in SDD terms?",
    [
      "More HOW — another framework name.",
      "Behaviour, edges, and acceptance criteria that would fail the “could this be built wrongly?” test.",
      "A screenshot of the Slack thread in CLAUDE.md.",
      "An MCP server for Slack, which would have made the spec unnecessary.",
    ],
    1,
    "A file list is not a spec. Unstated business rules are Clarify/Specify failures.",
  ),
  Q(
    "s13",
    "solo",
    "sdd",
    "You treat the spec as scaffolding, delete it after merge, and six weeks later change a subject line in code only. Users see a different product than anyone can point to. Name the failure.",
    [
      "Clarify skip",
      "Spec drift",
      "Plan mode leak",
      "KSOR overflow",
    ],
    1,
    "Spec-Anchored practice: behaviour changes update the spec first.",
  ),
  Q(
    "s14",
    "solo",
    "sdd",
    "A constitution demands mutation testing, coverage floors, and a four-phase loop for a one-line copy change. What SDD idea did you ignore?",
    [
      "Spec-as-Source is mandatory for copy.",
      "Right-sizing: trivial changes should not carry enterprise process.",
      "Research forbids looking at the file you will edit.",
      "Constitutions cannot mention tests.",
    ],
    1,
    "Match process weight to stakes. Over-strict constitutions are a named failure.",
  ),
  Q(
    "s15",
    "solo",
    "sdd",
    "After a green build you skip the design pass because tests passed. Weeks later the file is a tangle of duplicated helpers the agent added “just in case.” What was tests not covering?",
    [
      "Nothing; tests are the full definition of done in SDD.",
      "Structural health: coupling, duplication, decay — agents optimise for passing checks, not for a file you want to keep.",
      "MCP connectivity.",
      "Whether plan mode was on.",
    ],
    1,
    "SDD still requires a human design look. Generated code can be behaviour-correct and structurally bad.",
  ),
  Q(
    "s16",
    "solo",
    "sdd",
    "You write requirements so a competent builder could still ship a reset-password flow that leaks whether an email exists. The SDD tightening move is?",
    [
      "Name bcrypt in the spec.",
      "Add an acceptance criterion that makes the information leak a visible failure, then keep HOW out.",
      "Move the whole spec into a skill.",
      "Skip Clarify because security is implied.",
    ],
    1,
    "If a wrong-but-working build is possible, the spec is too weak. Tighten behaviour, not stack.",
  ),
  Q(
    "s17",
    "solo",
    "thesis",
    "You are asked whether the Agent Factory is a product you can buy. The thesis’s answer is?",
    [
      "Yes: it is a SaaS seat.",
      "No: it is a process for manufacturing AI-Native companies and Digital FTEs, using general agents under spec and supervision.",
      "Yes: it is OpenClaw with a different name.",
      "No: it is only a payments protocol (x402).",
    ],
    1,
    "Factory = process. Company = output. Workers = workforce.",
  ),
  Q(
    "s18",
    "solo",
    "thesis",
    "You need a one-off refactor this afternoon, not a standing employee. Which engagement mode is this, and which body of rules governs it?",
    [
      "Manufacturing, Seven Invariants",
      "Problem-solving, Seven Principles",
      "Identic, KSOR",
      "Economic-actor, AP2 mandates",
    ],
    1,
    "Mode 1 = immediate outcome, Seven Principles. Mode 2 = persistent worker, Seven Invariants.",
  ),
  Q(
    "s19",
    "solo",
    "thesis",
    "A vendor pitch says their agent can buy compute and pay invoices with no human in the loop. The thesis ties that trajectory to which 2025–2026 protocol cluster?",
    [
      "Only WebSockets",
      "ACP, AP2, x402, and MPP — agent-native authorization and micropayments",
      "SMTP and IMAP",
      "The Seven Principles",
    ],
    1,
    "Those four are the named rails for agents as economic actors.",
  ),
];
