import { Q } from "./helpers.ts";
import type { Question } from "../types.ts";

export const SOLO_A: Question[] = [
  Q(
    "s1",
    "solo",
    "agentic",
    "You notice the model is sorry, looping on the same patch, naming files that do not exist, and contradicting a constraint from earlier in the same thread. You still need the feature. What is the first action the course wants, before any new design talk?",
    [
      "Add the forgotten constraint to AGENTS.md and continue, since a rules-file edit is picked up on the next message of the same session.",
      "Write a longer recap of the constraints and resend it, since the model has clearly lost track of what was agreed earlier in the thread.",
      "Stop prompting: /compact if you still want this task, or /clear (or /new) for a clean start — a poisoned window is not repaired by prose.",
      "Switch to a stronger model inside the same thread, because the looping and the invented paths are symptoms of a capability ceiling.",
    ],
    2,
    "The diagnostic is explicit: stop typing; compact or clear; do not fix poison with more tokens.",
  ),
  Q(
    "s2",
    "solo",
    "agentic",
    "You want something that cannot be skipped: block git commit if lint or tests fail. You already have a paragraph in AGENTS.md that says the same thing, and the model still commits red. Which mechanism is missing?",
    [
      "A reviewer subagent that reads the diff before the commit lands, since isolation from the main thread makes the check harder to ignore.",
      "A sharper line in AGENTS.md, because the model reads the rules file on every message and a firmer phrasing is what was missing.",
      "A skill whose description mentions lint and tests, so the expertise is applied whenever the model judges the task to match.",
      "A hook or plugin on the commit path that returns the failure to the model as its next instruction, forming a loop it cannot skip.",
    ],
    3,
    "The verification loop is hook/plugin plus a check the model cannot decline.",
  ),
  Q(
    "s3",
    "solo",
    "agentic",
    "You keep typing the same “how we write API routes” briefing. It is not a hard gate, but you want it applied when that work comes up, without paying for it on unrelated turns. Where does it go?",
    [
      "A skill, invoked from its description when the matching work appears, running in the current window rather than on every turn.",
      "A slash command you invoke by hand, because anything you find yourself retyping belongs behind an explicit invocation.",
      "A hook on the file-write path, so the standard is enforced whenever a route file changes rather than remembered by the model.",
      "AGENTS.md, so the briefing is present on every turn and can never be forgotten by a session that starts fresh.",
    ],
    0,
    "Decision tree: auto expertise on match → skill. Subagent is for isolating heavy work, not for a playbook.",
  ),
  Q(
    "s4",
    "solo",
    "agentic",
    "You ask the main session to “find where we compute tax and dump everything you open.” Later the model forgets the plan you approved. Which concept did you violate first?",
    [
      "Prompt caching: opening dozens of files reset the stable front of the context and cost the session its discount.",
      "Context engineering: heavy reads belong in a subagent that returns a summary, not in the thread holding the plan.",
      "State persistence: the plan should have been written to a file, because chat is volatile and the approval was lost.",
      "Plan mode: the search should have been planned and approved before any file was opened in the main session.",
    ],
    1,
    "Search dumps are the classic way to poison the main window.",
  ),
  Q(
    "s5",
    "solo",
    "agentic",
    "You edited CLAUDE.md in the middle of a long session and the next message suddenly costs far more. The course’s cache note says what?",
    [
      "The cache is rebuilt at each compaction, so the cost will normalise at the next /compact and no habit needs to change.",
      "Nothing was violated: the cost rose because the rules file is now longer, and longer files cost more on every message.",
      "The discount holds only while the front of the context is stable, and editing the rules file resets that front.",
      "Editing rules mid-session forces a full re-read of the working tree, which is what the next message is being billed for.",
    ],
    2,
    "Prompt caching is a provider feature keyed on a stable prefix. Rules edits bust it.",
  ),
  Q(
    "s6",
    "solo",
    "agentic",
    "Claude Code undoes a bad edit with Esc Esc. A file the agent deleted via a shell command does not come back. Is that a bug relative to the course?",
    [
      "No, for another reason: deleted files are never recoverable in either tool, so git history is the only rollback that exists.",
      "Yes: the escape sequence should have been Esc Esc twice more, since a second rewind walks back the shell command as well.",
      "Yes: a checkpoint system that cannot restore a deleted file is incomplete, and the course treats that as a known defect.",
      "No: Claude Code's checkpointing covers the model's file edits, not shell side-effects; OpenCode's git-backed /undo is broader.",
    ],
    3,
    "The course flags this exact difference. Git remains the real history.",
  ),
  Q(
    "s7",
    "solo",
    "agentic",
    "You auto-approved every bash on day one, including rm and git push, because watching permissions felt slow. Which arc does the course describe instead?",
    [
      "Start by asking on every action, widen only for actions that have earned it, and keep a deny list for destructive commands.",
      "Never widen: the course keeps asking on every action indefinitely, since an approval once granted cannot be reasoned about later.",
      "Delegate the decision to the model: let it request escalation for the commands it judges risky, and approve those as they come.",
      "Approve everything on day one and rely on the deny list afterwards, because friction early is what makes people abandon the tool.",
    ],
    0,
    "Trust is earned session by session. Deny lists stay for rm -rf, publish, push.",
  ),
  Q(
    "s8",
    "solo",
    "agentic",
    "A stealth “free” model appears in /models under a codename. You are about to point it at a client repo. What two cautions does the course stack?",
    [
      "They are rate limited and slow, so a client repo should wait until the model graduates to a named, supported release.",
      "They are temporary and unannounced, and “free” may mean your prompts and code are the payment — so never for confidential work.",
      "They are unsupported by the tooling, so a client repo needs the named model for hooks, permissions and checkpoints to function.",
      "They are always smaller models, so a client repo needs the larger one for planning while the free model may execute the plan.",
    ],
    1,
    "Stealth models can vanish and may use your data. Use them for throwaway experiments.",
  ),
  Q(
    "s9",
    "solo",
    "agentic",
    "You are about to paste a full test run into the chat so the model can “see the failures.” The course’s cost/context habit is?",
    [
      "Ask a subagent to read the run and summarise it, since a summary of failures is cheaper than the run and easier to act on.",
      "Paste the failures only, trimmed to the failing test names, since a model that cannot see the stack traces cannot fix anything.",
      "Write the output to a file and report one line — path, count, where — because the file sits idle until it is searched.",
      "Raise the context ceiling for the session, because a test run is exactly the kind of content the model is meant to be given.",
    ],
    2,
    "Huge tool output in the transcript is paid again on every later turn and poisons attention.",
  ),
  Q(
    "s10",
    "solo",
    "agentic",
    "You want a second opinion on a diff. The same model that wrote the code is cheapest to use as reviewer. What does Part 8 claim?",
    [
      "Review is a human task at this stage; the course treats model-on-model review as a substitute for reading the diff yourself.",
      "The same model is fine if it reviews in a fresh session, since a clean context removes the assumptions that produced the error.",
      "The cheapest reviewer is the right reviewer, provided it is given the diff without the conversation that produced it.",
      "The writer shares the blind spots that caused the mistakes, so a different model — ideally a different provider — catches more.",
    ],
    3,
    "Cross-model review is the point of mixing providers. Same-model review still beats none, but it is weaker.",
  ),
  Q(
    "s11",
    "solo",
    "agentic",
    "You run five sessions on the same branch and they fight over files. The isolation pattern in the two-tools chapter is?",
    [
      "Git worktrees, or equivalent isolated checkouts, so that parallel sessions never share a single dirty working tree.",
      "Subagents inside one session, since a subagent's window is isolated and cannot conflict with the main thread over files.",
      "Sequential sessions with a compaction between each, so the second session inherits the first one's file state cleanly.",
      "One session per branch with a shared working tree, coordinating through the rules file so each knows which files are taken.",
    ],
    0,
    "Parallelize only with isolation. Cherny’s own workflow is multiple checkouts.",
  ),
  Q(
    "s12",
    "solo",
    "sdd",
    "Your “spec” is a list of files to create and a chosen ORM. Build succeeds and still misses a business rule that was only in a Slack paragraph. What was the spec missing, in SDD terms?",
    [
      "A file map and a chosen stack, which is what stops an agent from inventing an architecture of its own during the build.",
      "Behaviour, edges, and acceptance criteria — the content that would fail the “could this be built wrongly?” test.",
      "A constitution listing the durable constraints, since a business rule from Slack is a principle rather than a requirement.",
      "A Clarify transcript attached to the spec, so the Slack paragraph is preserved as evidence of the original intent.",
    ],
    1,
    "A file list is not a spec. Unstated business rules are Clarify/Specify failures.",
  ),
  Q(
    "s13",
    "solo",
    "sdd",
    "You treat the spec as scaffolding, delete it after merge, and six weeks later change a subject line in code only. Users see a different product than anyone can point to. Name the failure.",
    [
      "Scope creep — the change grew past what the original request described",
      "Agent drift — the builder deviated from the plan partway through the work",
      "Spec drift — the code changed and the specification was never updated",
      "Constitutional decay — the durable principles outlived their usefulness",
    ],
    2,
    "Spec-Anchored practice: behaviour changes update the spec first.",
  ),
  Q(
    "s14",
    "solo",
    "sdd",
    "A constitution demands mutation testing, coverage floors, and a four-phase loop for a one-line copy change. What SDD idea did you ignore?",
    [
      "The failure test, which asks whether a competent builder could satisfy the requirement wrongly if it were left as it is.",
      "Spec-as-Source, where the code is ephemeral and the ceremony around any single change is therefore deliberately heavy.",
      "Spec-Anchored practice, which requires the constitution to be applied uniformly to every change however small it is.",
      "Right-sizing: a trivial one-line change should not carry the full enterprise process built for architectural work.",
    ],
    3,
    "Match process weight to stakes. Over-strict constitutions are a named failure.",
  ),
  Q(
    "s15",
    "solo",
    "sdd",
    "After a green build you skip the design pass because tests passed. Weeks later the file is a tangle of duplicated helpers the agent added “just in case.” What was tests not covering?",
    [
      "Structural health — coupling, duplication, decay; agents optimise for passing checks, not for a file you want to keep.",
      "Verification independence: the checks were authored by the same agent, so a green build was never evidence of anything.",
      "Observability: nothing recorded why the helpers were added, so the duplication could not be diagnosed until it spread.",
      "Behavioural correctness: the tests passed because they only exercised the paths the agent had itself decided to write.",
    ],
    0,
    "SDD still requires a human design look. Generated code can be behaviour-correct and structurally bad.",
  ),
  Q(
    "s16",
    "solo",
    "sdd",
    "You write requirements so a competent builder could still ship a reset-password flow that leaks whether an email exists. The SDD tightening move is?",
    [
      "Name the hashing algorithm and the response shape, since an information leak can only be closed by fixing the mechanism.",
      "Add an acceptance criterion that makes the information leak a visible failure, while keeping the HOW out of the spec.",
      "Move the requirement into the constitution, where a durable principle can forbid enumeration without naming a mechanism.",
      "Tighten the Clarify interview until the builder cannot misread the flow, since ambiguity is what allowed the leak through.",
    ],
    1,
    "If a wrong-but-working build is possible, the spec is too weak. Tighten behaviour, not stack.",
  ),
  Q(
    "s17",
    "solo",
    "thesis",
    "You are asked whether the Agent Factory is a product you can buy. The thesis’s answer is?",
    [
      "No: it is an org chart rather than a product, describing who supervises the AI workers once they have been hired.",
      "Yes: it is licensed per seat, and the thesis describes the pricing model that goes with a mostly-AI workforce.",
      "No: it is a process for manufacturing AI-Native companies and Digital FTEs, using general agents under spec and supervision.",
      "Yes, but only the manufacturing half; the problem-solving mode is a service engagement rather than something you buy.",
    ],
    2,
    "Factory = process. Company = output. Workers = workforce.",
  ),
  Q(
    "s18",
    "solo",
    "thesis",
    "You need a one-off refactor this afternoon, not a standing employee. Which engagement mode is this, and which body of rules governs it?",
    [
      "Manufacturing, governed by the four-phase spec-driven development loop",
      "Problem-solving, governed by the Seven Invariants of the thesis",
      "Manufacturing, governed by the Seven Invariants of the operating layer",
      "Problem-solving, governed by the Seven Principles of general agents",
    ],
    3,
    "Mode 1 = immediate outcome, Seven Principles. Mode 2 = persistent worker, Seven Invariants.",
  ),
  Q(
    "s19",
    "solo",
    "thesis",
    "A vendor pitch says their agent can buy compute and pay invoices with no human in the loop. The thesis ties that trajectory to which 2025–2026 protocol cluster?",
    [
      "ACP, AP2, x402 and MPP — agent-native authorization and micropayments",
      "ISO 20022, SEPA Instant, SWIFT gpi and the card network token vaults",
      "MCP, ACP, Skills and the Agent Client Protocol used by host applications",
      "OAuth 2.1, OpenID Connect, WebAuthn and the FIDO2 attestation chain",
    ],
    0,
    "Those four are the named rails for agents as economic actors.",
  ),
];
