import { Q } from "./helpers.ts";
import type { Question } from "../types.ts";

export const SOLO_B: Question[] = [
  Q(
    "s20",
    "solo",
    "thesis",
    "Your company “uses AI” inside the IT ticket queue. A board paper quotes Griggs: confining AI to IT is how you miss the transformation. What relocation does the thesis want?",
    [
      "Move the ticket queue onto a larger model, since the transformation Griggs describes is a capability change rather than a structural one.",
      "Treat AI as a workforce with specs, records, management and verification — a business change of people and process, not a tool in IT.",
      "Move the queue out of IT and into the business units, so each department owns its own agents and its own model budget going forward.",
      "Replace the queue with an identic agent per employee, since the edge layer is where the thesis says personal delegation belongs.",
    ],
    1,
    "The PwC thread is not “buy a larger model for helpdesk.”",
  ),
  Q(
    "s21",
    "solo",
    "problem",
    "You watch the agent narrate a beautiful plan and never touch the folder you named. Which principle failed first?",
    [
      "P6 Constraints — a folder that was never named in the permissions could not be touched even if the agent had tried.",
      "P7 Observability — you could see the plan but not the execution, which is the same failure wearing a different name.",
      "P1 Bash is the Key — you briefed the brain for an essay rather than briefing the hands for an artifact.",
      "P3 Verification — nothing checked the plan against the folder, so the narration went unchallenged until the work was due.",
    ],
    2,
    "If it only talks, you asked a question. Instruct an action with an output path.",
  ),
  Q(
    "s22",
    "solo",
    "problem",
    "You combine explore, plan, and implement in one prompt “to save a round trip.” The tree is half-migrated. Name the pattern.",
    [
      "Scope creep, from a prompt that named no boundary at all around the table migration",
      "Black Box, from an execution whose individual steps were never surfaced to the human",
      "Drift, from a plan that was never written down where a later session could go and find it",
      "Big Bang, from skipped decomposition and skipped Explore and Plan gates before the work began",
    ],
    3,
    "The four-phase loop exists so each gate is reversible. Collapsing it is Big Bang.",
  ),
  Q(
    "s23",
    "solo",
    "problem",
    "Yesterday’s decisions are gone because they lived only in chat. You are re-explaining the same constraints. The principle that names this is?",
    [
      "P5 Persist state in files — chat is volatile, so plans, rules and explore notes belong on disk.",
      "P2 Code as interface — the constraints should have been expressed as a schema the agent could not misread.",
      "P4 Small reversible steps — a decision that cannot be re-derived is a decision that was never decomposed.",
      "P7 Observability — the decisions were made but never surfaced in a form anyone could review afterwards.",
    ],
    0,
    "Files, not transcripts, are memory. Rules and plan files are P5.",
  ),
  Q(
    "s24",
    "solo",
    "problem",
    "The agent edited a folder you never named. Your prompt was broad (“clean this up”) and permissions were wide. Which pairing is the course’s diagnosis?",
    [
      "Drift + P5, because the folder was named in chat and never written to a file the agent could be held to.",
      "Scope Creep + P6, because a broad prompt plus wide permissions is a boundary problem rather than a model problem.",
      "Confident Wrong + P3, because the agent believed the cleanup was correct and nothing independent checked it.",
      "Big Bang + P4, because one instruction covered more of the tree than a single reversible step should carry.",
    ],
    1,
    "Unauthorised touch is Scope Creep. Constraints and allow/deny lists are the lever.",
  ),
  Q(
    "s25",
    "solo",
    "problem",
    "You cannot tell what the agent actually ran; you only see a final paragraph. In Cowork you ignored the step cards. Which principle?",
    [
      "P6 Constraints — approving without reading is what turned a wide permission set into an unauditable one.",
      "P3 Verification — a final paragraph is a claim, and nothing in the session checked it against the repository.",
      "P7 Observability — you can only direct what you can see, and the step cards were the only seeing available.",
      "P1 Bash is the Key — the run should have produced an artifact you could inspect rather than a summary of itself.",
    ],
    2,
    "Terminal traces, Cowork cards, OpenWork timeline — watch the hands.",
  ),
  Q(
    "s26",
    "solo",
    "problem",
    "A prose request for a comparison keeps coming back as an inconsistent essay. What does P2 want you to specify first?",
    [
      "The rubric, so a human can score each comparison against the same criteria instead of judging the prose.",
      "The sources, since an inconsistent comparison is usually a symptom of the agent reading different material each time.",
      "The audience, since an essay that keeps changing tone is an essay whose reader was never named in the request.",
      "The shape: a table or schema with the columns the agent must fill, rather than a paragraph it can arrange freely.",
    ],
    3,
    "Code/schema as universal interface kills prose ambiguity.",
  ),
  Q(
    "s27",
    "solo",
    "openclaw",
    "Gateway is up on 18789 but a new MCP server does nothing. You did not restart after configuring. Which ritual did you skip?",
    [
      "The activation dance: exists → disabled → enabled → configured, and then a gateway restart before it will run.",
      "The brain-file reload, since MEMORY.md must mention a connector before the gateway will expose it to the model.",
      "The workspace prune, because a bloated workspace is the usual reason a newly added server fails to appear at all.",
      "The credential rotation, since a new MCP server cannot reach its tools until the keys in the credentials store are refreshed.",
    ],
    0,
    "Extensions load on gateway restart. Silent MCP is a log-and-restart problem.",
  ),
  Q(
    "s28",
    "solo",
    "openclaw",
    "Workspace markdown has grown to tens of pages and every WhatsApp reply is slow and expensive. The course’s lean-brain rule is?",
    [
      "Prune the workspace weekly, because a slow reply is usually a symptom of files accumulating rather than of context size.",
      "Keep brain files short, about a page or two; bloat is a context cost paid on every turn, so length is a running cost.",
      "Move older pages into a separate archive folder, so the gateway can search them on demand instead of loading them always.",
      "Switch the channel to a cheaper model, since WhatsApp replies do not need the same depth as the long-running sessions.",
    ],
    1,
    "Same context-engineering idea: idle text is a tax.",
  ),
  Q(
    "s29",
    "solo",
    "openclaw",
    "Docs in the downloaded AGENTS.md disagree with docs.openclaw.ai/llms.txt. What is the stated source-of-truth order?",
    [
      "Whichever of the three agrees with the others, since a majority vote across sources is the only safe reading here.",
      "Local file > live docs > log, since a file you have downloaded is the only artifact you can be sure is unchanged.",
      "Live docs > local file > log — the shipped documentation can be older than the release you are actually running.",
      "Log > live docs > local file, since the running gateway is the only source that reflects the version you installed.",
    ],
    2,
    "The OpenClaw course is explicit: live docs, then the file, then the log.",
  ),
  Q(
    "s30",
    "solo",
    "openclaw",
    "You want a reminder every weekday at 09:00 versus a nudge every 30 minutes while you work. Which pair is which?",
    [
      "Cron is clock time, heartbeat is event triggers, and hooks are the ambient interval.",
      "Cron is clock time, heartbeat is clock time at a finer grain, and hooks are event triggers.",
      "Cron is ambient interval, heartbeat is clock time, and hooks are event triggers.",
      "Cron is clock time, heartbeat is ambient interval, and hooks are event triggers.",
    ],
    3,
    "Cron / heartbeat / hooks are distinct schedulers.",
  ),
  Q(
    "s31",
    "solo",
    "openclaw",
    "Something is broken. The recovery prompt the course wants you to approve is closest to which shape?",
    [
      "Read the gateway log, explain in plain language, propose a fix you can approve — and no new architecture in the same breath.",
      "Collect the last twenty turns, summarise them into a fresh session, and re-ask the question with the summary attached.",
      "Disable the suspect connector, wait for the next heartbeat, and confirm the symptom has gone before touching anything else.",
      "Restart the gateway and clear the workspace, then re-add the connectors from scratch if the problem still appears.",
    ],
    0,
    "Log → plain language → approve. Budget overruns mean re-plan, not extra flailing.",
  ),
  Q(
    "s32",
    "solo",
    "layer",
    "You need on-device loops for a sensitive matter. The operating-layer invariant this appeals to is?",
    [
      "The OS recedes as the thing humans click, so sensitive work should run where the user cannot see it happening at all.",
      "Local compute for privacy, latency and sensitive work — the layer is not only a cloud API and need not be one here.",
      "Agents belong inside the OS substrate rather than beside it, which is why an on-device loop is the safer of the two.",
      "The layer is a place to run, not a product, so a sensitive loop should sit in the runtime that has the fewest users.",
    ],
    1,
    "Local compute is listed as an invariant, not an optional luxury.",
  ),
  Q(
    "s33",
    "solo",
    "layer",
    "A knowledge team’s “source of truth” is a rotating chat. Models change quarterly and the method documents vanish. What construct was the course trying to get you to own?",
    [
      "An evaluation suite: a set of questions the team runs each quarter, so the loss is detected when the model changes.",
      "A prompt pack: reusable requests that survive a model swap because they carry their own context inside the request.",
      "A Knowledge System of Record — sources, policy, methods, provenance and the context that must survive a model swap.",
      "A governance board: named owners for each knowledge domain, so a rotating chat cannot be the only place it lives.",
    ],
    2,
    "KSOR is the knowledge-work analogue of the transactional system of record.",
  ),
  Q(
    "s34",
    "solo",
    "layer",
    "Windows ODR and Agent Launchers, macOS ACP hosting, Linux shell+files: these are examples of what claim?",
    [
      "Operating systems are becoming containment layers, because the shell, files and launchers are how an agent is bounded.",
      "Operating systems are becoming distribution channels, since launchers and hosting are how agents reach ordinary users.",
      "Operating systems are becoming products again, since discovery and invocation are features a vendor now ships to users.",
      "Operating systems are growing substrates for discovery, invocation and containment while receding as what humans click.",
    ],
    3,
    "OS as plumbing plus new discovery/containment surfaces.",
  ),
  Q(
    "s35",
    "solo",
    "layer",
    "You give an agent send-on-all-mailers with no threshold. It dispatches a wrong customer notice. The governance miss is?",
    [
      "Over-delegation without permissions, thresholds, audit and reversible actions around a send that could not be taken back.",
      "Missing verification: the notice should have been checked against the customer record before it was queued for sending.",
      "Missing observability: the dispatch was visible in the log, but nobody was assigned to read the log before it went out.",
      "Model failure: a customer notice is high-stakes enough that no current model should have been trusted to draft it.",
    ],
    0,
    "Governance/audit is a layer, not a vibe. Draft-vs-send is the canonical threshold.",
  ),
  Q(
    "s36",
    "solo",
    "agentic",
    "You are choosing between a slash command you always type and a skill you want the model to notice. The decision tree says?",
    [
      "If it is short enough to type, command; if the instructions are longer than the request that would trigger them, skill.",
      "If you invoke it yourself on purpose, it is a command; if it should apply when the task matches, it is a skill.",
      "If it needs arguments, command; if it needs only a description the model can read, skill, regardless of who triggers it.",
      "If it touches the filesystem, command, because skills run read-only; if it only reasons about the task, then it is a skill.",
    ],
    1,
    "Manual repeat → command. Auto expertise → skill.",
  ),
  Q(
    "s37",
    "solo",
    "sdd",
    "Clarify is running as a dump of twenty questions in one message, several of which smuggle implementation. The course’s interview rule is?",
    [
      "Ask the twenty questions, then write the answers into the spec so nothing has to be asked twice in a later session.",
      "Skip clarify and go straight to a draft spec, since a wrong assumption is cheaper to correct than twenty questions.",
      "One question at a time and no code at all, until the spec is hard for a reader to misread.",
      "Batch the questions, but keep them to decisions only; implementation detail belongs in the plan, never in clarify.",
    ],
    2,
    "Cheap, serial disambiguation. Implementation talk belongs in plan, not Clarify.",
  ),
  Q(
    "s38",
    "solo",
    "thesis",
    "Cherny’s published workflow is called “vanilla”: short shared rules, plan before non-trivial work, a way for the model to verify, many sessions. A junior on your team is collecting prompt packs instead. Where does the agentic-coding ladder say people stall?",
    [
      "Below first sessions altogether — the junior has not yet learned to run a task with a model rather than around one.",
      "Between a rules file and the team level, because a shared file is a team artifact and the junior is still writing alone.",
      "Between never explain twice and a team that runs on it — the rules file exists but nobody has made it the team's standard.",
      "Between first sessions and never explain twice: collecting prompts instead of building a rules file as a living system.",
    ],
    3,
    "The course says most people stall between stages 1 and 2, hoarding prompts.",
  ),
  Q(
    "s39",
    "solo",
    "thesis",
    "You have been asked to tell the board whether the company is AI-Native. Which test does the thesis give you?",
    [
      "Whether the workforce is mostly AI, and the product is whatever that workforce produces for the customers.",
      "Whether the model choice is treated as a business decision rather than a procurement decision made by the IT function.",
      "Whether AI appears in the org chart as a cost centre with named owners, rather than as a vendor line in the IT budget.",
      "Whether the product is built with AI assistance and the roadmap is reviewed by people who understand the model limits.",
    ],
    0,
    "The definition is about who does the work and what the output is, not about tooling adoption or PR share.",
  ),
  Q(
    "s40",
    "solo",
    "thesis",
    "An engagement is being scoped and you must classify it. Which discriminator does the thesis use?",
    [
      "An engagement that ships software is problem-solving; an engagement that ships an operating capability is manufacturing.",
      "An immediate outcome under the Seven Principles is problem-solving; a persistent AI Worker under the Seven Invariants is manufacturing.",
      "An outcome the client uses once is problem-solving; an outcome the client operates daily is manufacturing, whatever it ships.",
      "An engagement scoped by principles is problem-solving; one scoped by invariants is manufacturing, since invariants persist.",
    ],
    1,
    "The two modes differ in what they leave behind: a result, or a worker that keeps working.",
  ),
  Q(
    "s41",
    "solo",
    "thesis",
    "You need the reskilling figure from the WEF Future of Jobs 2025 report to justify a training budget. Which number does the canon quote?",
    [
      "59 of every 100 workers will have been displaced by 2030, according to the report as quoted",
      "59 of every 100 workers will need reskilling by 2035, according to the report as quoted",
      "59 of every 100 workers will need reskilling by 2030, according to the report as quoted",
      "59 of every 100 employers will need to reskill staff by 2030, according to the report",
    ],
    2,
    "59 in 100 need reskilling by 2030. The 56% figure is the PwC CEO-survey result about AI returning no financial value, and 35% is Cursor's agent-written PR share.",
  ),
  Q(
    "s42",
    "solo",
    "agentic",
    "Your session died mid-task. The plan is saved at docs/plans/billing-split.md. What is the sequence the course endorses?",
    [
      "Run claude --resume or OpenCode /sessions repeatedly until the session returns, since a dead session cannot be replaced.",
      "Re-run the whole plan from step one in a fresh session, since a partial migration cannot be trusted to resume safely anyway.",
      "Start a fresh session, paste the last twenty turns into it, and let the new model reconstruct where the plan had reached.",
      "Try resume first; if it fails, start a fresh session, tell it to read docs/plans/billing-split.md and continue from a named step.",
    ],
    3,
    "Resume is the convenience; the plan file is the durable contract that survives the conversation.",
  ),
  Q(
    "s43",
    "solo",
    "agentic",
    "Your rules file has grown to 200 lines and you keep adding a prohibition after every mistake. What does the course tell you to do with it?",
    [
      "Add a line when a real mistake happens, prune lines that stop earning their place, and prefer describing the standard over forbidding.",
      "Split it into per-project files so each session loads only the prohibitions that apply to the repository it is working in.",
      "Move the prohibitions into a memory file, so the rules file stays a short statement of the standard rather than a list.",
      "Rewrite it from scratch each quarter, since a rules file that has only ever grown is a record of past mistakes rather than a standard.",
    ],
    0,
    "A huge rules file is a recurring cost on every message. Anthropic's own pruning of 80%+ of its system prompt is the model to follow.",
  ),
  Q(
    "s44",
    "solo",
    "agentic",
    "You need a sweep of 400 files to find every caller of a deprecated helper, and you do not want the transcript buried in matches. What does the course reach for?",
    [
      "A grep with a count flag, so the transcript records how many matches were found rather than listing every one of them.",
      "A subagent: the heavy reading happens off-thread, so the main chat receives a summary instead of the matches.",
      "A custom command, since a four-hundred-file sweep is exactly the kind of repeated invocation a command is meant to hold.",
      "A separate scratchpad file, so the agent can write matches to disk and the transcript stays free of them while it works.",
    ],
    1,
    "Isolating heavy reading is what subagents are for. The built-in Explore agent is the cheap read-only case of the same idea.",
  ),
  Q(
    "s45",
    "solo",
    "agentic",
    "Every release you type the same four-step instruction to produce release notes, and you always want to trigger it yourself. What does the decision tree prescribe?",
    [
      "A rules-file entry, because a release procedure is a standard the project holds and should apply to every session.",
      "A skill, because release notes have a recognisable shape and the model should apply them whenever a release is prepared.",
      "A slash or custom command, because this is a repeated manual invocation that you want to trigger yourself every time.",
      "A subagent, because the four steps involve reading the diff and the tickets, which is work that belongs off-thread.",
    ],
    2,
    "Same thing, repeatedly, by hand: that is a command. Skills are for expertise the model should apply on its own judgment.",
  ),
  Q(
    "s46",
    "solo",
    "agentic",
    "You let an agent run a bash migration that altered a table, then used Claude Code's Esc-Esc /rewind to go back. What is true of your database?",
    [
      "It was rolled back only if the migration ran inside a transaction the shell had opened before the agent took control.",
      "It depends on the driver: a rewind issued from the CLI undoes the shell as well, one issued from the editor does not.",
      "It was rolled back too, since rewind restores the working state the session observed when the migration was run.",
      "It was not: rewind undoes file edits, not bash side effects. OpenCode's /undo is git-backed; neither replaces git.",
    ],
    3,
    "Checkpoints are not git history, and rewind does not reach the database.",
  ),
  Q(
    "s47",
    "solo",
    "sdd",
    "Your spec has a goal, scenarios, functional requirements and acceptance criteria, but no out-of-scope section. What risk does the course attach to that omission?",
    [
      "Scope creep, and a competent builder satisfying the spec wrongly — out of scope is one of the things a spec is expected to contain.",
      "Rework, because the reviewer has no basis on which to reject an implementation that wanders outside the stated goal.",
      "Estimation drift, since the builder cannot size the work without knowing which adjacent areas it is not being asked to enter.",
      "Ambiguity, because acceptance criteria without an exclusion list can be read as covering more than the author intended.",
    ],
    0,
    "A spec says what is in and what is out. Without the boundary, both drift and wrong satisfaction become likely.",
  ),
  Q(
    "s48",
    "solo",
    "sdd",
    "For three sprints the code has moved and nobody has touched the spec. What is the named failure, and how does it differ from the agent's own mid-build wandering?",
    [
      "Agent drift — the builder wandered while implementing — as distinct from spec drift, a spec too loose to constrain it.",
      "Spec drift — the code changing without the spec — as distinct from agent drift, which is the agent deviating mid-build.",
      "Stale spec — a document nobody has read since the build began — as distinct from a living spec that is updated as work proceeds.",
      "Silent divergence — code and spec moving apart with no owner — as distinct from the drift a reviewer is expected to catch.",
    ],
    1,
    "Two names, two directions: the code outrunning the document, and the builder outrunning the plan.",
  ),
  Q(
    "s49",
    "solo",
    "sdd",
    "You cite Anthropic's 2026 study of 400,000 agentic sessions in a design review. What conclusion does the course draw from it?",
    [
      "That most sessions end without a verified artifact, so the budget belongs in verification rather than in generation.",
      "That agents are reliable enough for routine work but not for judgment, so the review step is what the investment should buy.",
      "A what/how split: humans frame the problem, agents execute — so the framing work is the part worth investing in.",
      "That session length is the constraint, so the design work should go into decomposition rather than into the prompt.",
    ],
    2,
    "The volume is evidence for the division of labour, not for removing the human from the framing.",
  ),
  Q(
    "s50",
    "solo",
    "problem",
    "Your agent finishes and reports that the implementation looks right. Nothing else has been run. What does the canon ask for next?",
    [
      "A second reading of the transcript by the person who asked, to confirm the agent did what the request actually said.",
      "A checkpoint commit before the next step, so the work is recoverable if a later review finds something to disagree with.",
      "A diff review by the agent itself, reading its own changes line by line against the spec it was originally given.",
      'An independent check — tests, a rubric, quote-the-source, or a cross-model review — because "looks right" is the failure mode.',
    ],
    3,
    "P3 is about a check that does not depend on the author's confidence. The writer is the worst reviewer of their own code.",
  ),
  Q(
    "s51",
    "solo",
    "problem",
    "You are tempted to hand an agent a six-hour rewrite in one instruction and come back to a finished system. Which principle and which failure pattern does the course pair against that?",
    [
      "P4 small reversible decomposition — atomic units with git or checkpoints between them — against the Big Bang pattern.",
      "P6 constraints — a wide permission set with no boundary — against the Over-delegation pattern, where the agent outruns you.",
      "P7 observability — a run you cannot see inside — against the Black Box pattern, where approval is given without reading.",
      "P3 verification — nothing independent checks the result — against the Confident Wrong pattern, where the model is sure.",
    ],
    0,
    "Reversibility is what makes a long build survivable. Big Bang is the named failure when it is missing.",
  ),
  Q(
    "s52",
    "solo",
    "problem",
    "Your plan exists only as messages in a chat that you have now lost. Which principle did you skip, and what should have been on disk?",
    [
      "P2 code as interface — a spec.md should have carried the plan, since prose in chat cannot be enforced by a contract.",
      "P5 persist state in files — plans, rules and explore.md belong on disk, because chat itself is volatile.",
      "P4 small reversible steps — a checkpoint per step would have left a trail of state you could reconstruct the plan from.",
      "P7 observability — the plan should have been written where a later reader could see the reasoning that produced it.",
    ],
    1,
    "Chat is not storage. Drift is the failure pattern that P5 answers.",
  ),
  Q(
    "s53",
    "solo",
    "problem",
    "A non-technical programme manager needs to run agents on real work without a terminal. What does the course recommend, and what carries over?",
    [
      "A chat channel the manager already has, so no new surface is introduced and no new approval flow has to be learned.",
      "A hosted web agent with an approval inbox, since the browser is the only surface a programme manager already uses daily.",
      "A desktop surface such as Cowork or OpenWork with approval cards — the principles transfer, the surfaces differ.",
      "A guided CLI wrapper with saved presets, since the terminal is still where the agent's real permissions actually live.",
    ],
    2,
    "Approval cards are the desktop answer to the same P6 problem the shell solves with permissions.",
  ),
  Q(
    "s54",
    "solo",
    "openclaw",
    "You edited SOUL.md and IDENTITY.md this morning and the assistant still behaves exactly as it did yesterday. Which listed pitfall have you most likely hit?",
    [
      "Forgetting to mention the new persona in MEMORY.md, so the model has no reason to behave differently from yesterday.",
      "Editing files outside the workspace the gateway is configured to read, so the instance never sees the change at all.",
      "Editing the brain files without restarting the gateway, so the running process still holds the version it loaded at boot.",
      "Forgetting /reset after brain edits, so the running instance is still carrying the old files rather than the new ones.",
    ],
    3,
    "Brain edits need /reset. The files are not re-read by a running instance on their own.",
  ),
  Q(
    "s55",
    "solo",
    "openclaw",
    "You ask a general agent to install and configure OpenClaw from a folder containing AGENTS.md. Which parts of the job stay with you?",
    [
      "The human seams — QR pairing and API keys — while the agent handles installation and configuration from the folder.",
      "The verification pass — confirming the install actually works — while the agent handles the folder and the config file.",
      "The rollback plan — knowing how to remove it cleanly — while the agent handles the install and the configuration steps.",
      "The permissions decision — which folders and channels the agent may touch — while the agent handles the install itself.",
    ],
    0,
    "The split is deliberate: agents do the mechanical work, humans hold the credentials and the device pairing.",
  ),
  Q(
    "s56",
    "solo",
    "layer",
    "Your legal team requires that certain sensitive loops never leave the machine. Which invariant of the layer answers that requirement?",
    [
      "Agents belong inside the OS, and a machine-local loop is the natural home for a sensitive one",
      "Local compute for private and sensitive loops, which is what the layer is for",
      "The OS recedes as what humans click, so a private loop should be invisible to them by design",
      "A layer is a place to run rather than a product, so the runtime choice is a governance decision",
    ],
    1,
    "Local compute is the named invariant for private work. Trusted records answer a different question — where authoritative state lives.",
  ),
  Q(
    "s57",
    "solo",
    "layer",
    "You cite the Klarna example — an agent handling roughly two thirds of chats, about 700 employees' worth, around $40M of profit impact. What does the layer text use it to show?",
    [
      "That chat is the easiest domain to automate, and the example is included to show where the layer will land next.",
      "That cost reduction is the honest measure of an agent programme, and the profit figure is the argument to make to a board.",
      "That bounded production work at scale is already real, which is why governance and hybrid review belong in the layer.",
      "That headcount equivalence is the wrong metric, since the agents handled volume that the employees were never assigned to.",
    ],
    2,
    "The example shows scale, not infallibility. The course pairs it with the point that reliability is not 100%.",
  ),
];
