import { Q } from "./helpers";
import type { Question } from "../types";

export const SOLO_B: Question[] = [
  Q(
    "s20",
    "solo",
    "thesis",
    "Your company “uses AI” inside the IT ticket queue. A board paper quotes Griggs: confining AI to IT is how you miss the transformation. What relocation does the thesis want?",
    [
      "Bigger GPUs in the same ticket queue.",
      "Treat AI as a workforce with specs, records, management, and verification — a business change of people and process.",
      "Replace the board with an identic agent.",
      "Ban MCP.",
    ],
    1,
    "The PwC thread is not “buy a larger model for helpdesk.”",
  ),
  Q(
    "s21",
    "solo",
    "problem",
    "You watch the agent narrate a beautiful plan and never touch the folder you named. Which principle failed first?",
    [
      "P7 Observability — you could not see",
      "P1 Bash is the Key — you briefed the brain for an essay, not the hands for an artifact",
      "P6 — you needed a sandbox",
      "P3 — you needed mutation tests",
    ],
    1,
    "If it only talks, you asked a question. Instruct an action with an output path.",
  ),
  Q(
    "s22",
    "solo",
    "problem",
    "You combine explore, plan, and implement in one prompt “to save a round trip.” The tree is half-migrated. Name the pattern.",
    [
      "Black Box",
      "Big Bang from skipped decomposition (and skipped Explore/Plan gates)",
      "Scope Creep only",
      "Identic overflow",
    ],
    1,
    "The four-phase loop exists so each gate is reversible. Collapsing it is Big Bang.",
  ),
  Q(
    "s23",
    "solo",
    "problem",
    "Yesterday’s decisions are gone because they lived only in chat. You are re-explaining the same constraints. The principle that names this is?",
    [
      "P2 Code as interface",
      "P5 Persist state in files (chat is volatile)",
      "P7 only",
      "P1 only",
    ],
    1,
    "Files, not transcripts, are memory. Rules and plan files are P5.",
  ),
  Q(
    "s24",
    "solo",
    "problem",
    "The agent edited a folder you never named. Your prompt was broad (“clean this up”) and permissions were wide. Which pairing is the course’s diagnosis?",
    [
      "Drift + P2",
      "Scope Creep + P6 constraints/permissions",
      "Confident Wrong + P5",
      "Black Box + constitution",
    ],
    1,
    "Unauthorised touch is Scope Creep. Constraints and allow/deny lists are the lever.",
  ),
  Q(
    "s25",
    "solo",
    "problem",
    "You cannot tell what the agent actually ran; you only see a final paragraph. In Cowork you ignored the step cards. Which principle?",
    [
      "P3 only",
      "P7 Observability — you can only direct what you can see",
      "P1 forbids GUIs",
      "P4 forbids desktop tools",
    ],
    1,
    "Terminal traces, Cowork cards, OpenWork timeline — watch the hands.",
  ),
  Q(
    "s26",
    "solo",
    "problem",
    "A prose request for a comparison keeps coming back as an inconsistent essay. What does P2 want you to specify first?",
    [
      "A warmer tone",
      "The shape: a table/schema with columns the agent must fill, not a paragraph",
      "A stealth model",
      "MCP to a spreadsheet, which replaces P2",
    ],
    1,
    "Code/schema as universal interface kills prose ambiguity.",
  ),
  Q(
    "s27",
    "solo",
    "openclaw",
    "Gateway is up on 18789 but a new MCP server does nothing. You did not restart after configuring. Which ritual did you skip?",
    [
      "Monthly audit only",
      "The activation dance: exists → disabled → enabled → configured, then gateway restart",
      "Rewriting SOUL.md",
      "Switching to plan mode in Claude Code",
    ],
    1,
    "Extensions load on gateway restart. Silent MCP is a log-and-restart problem.",
  ),
  Q(
    "s28",
    "solo",
    "openclaw",
    "Workspace markdown has grown to tens of pages and every WhatsApp reply is slow and expensive. The course’s lean-brain rule is?",
    [
      "Put everything in MEMORY.md so nothing is lost.",
      "Keep brain files short (about a page or two); bloat is context cost on every turn.",
      "Disable the gateway.",
      "Move MEMORY.md into CLAUDE.md in the client repo.",
    ],
    1,
    "Same context-engineering idea: idle text is a tax.",
  ),
  Q(
    "s29",
    "solo",
    "openclaw",
    "Docs in the downloaded AGENTS.md disagree with docs.openclaw.ai/llms.txt. What is the stated source-of-truth order?",
    [
      "MEMORY.md > live docs > log",
      "Live docs > local file > log",
      "GitHub stars > Jensen Huang quotes > docs",
      "The constitution in the client repo always wins.",
    ],
    1,
    "The OpenClaw course is explicit: live docs, then the file, then the log.",
  ),
  Q(
    "s30",
    "solo",
    "openclaw",
    "You want a reminder every weekday at 09:00 versus a nudge every 30 minutes while you work. Which pair is which?",
    [
      "Heartbeat is the clock; cron is the interval.",
      "Cron is clock time; heartbeat is ambient interval; hooks are event triggers.",
      "All three are MCP servers.",
      "Skills replace schedules.",
    ],
    1,
    "Cron / heartbeat / hooks are distinct schedulers.",
  ),
  Q(
    "s31",
    "solo",
    "openclaw",
    "Something is broken. The recovery prompt the course wants you to approve is closest to which shape?",
    [
      "Reinstall Node and hope.",
      "Read the gateway log, explain in plain language, propose a fix you can approve — do not improvise a new architecture in the same breath.",
      "Paste SOUL.md into Discord.",
      "Disable all skills forever.",
    ],
    1,
    "Log → plain language → approve. Budget overruns mean re-plan, not extra flailing.",
  ),
  Q(
    "s32",
    "solo",
    "layer",
    "You need on-device loops for a sensitive matter. The operating-layer invariant this appeals to is?",
    [
      "Models must be frontier and cloud-only.",
      "Local compute for privacy, latency, and sensitive work — the OS/layer is not only a cloud API.",
      "KSOR forbids local files.",
      "ACP cannot run on Linux.",
    ],
    1,
    "Local compute is listed as an invariant, not an optional luxury.",
  ),
  Q(
    "s33",
    "solo",
    "layer",
    "A knowledge team’s “source of truth” is a rotating chat. Models change quarterly and the method documents vanish. What construct was the course trying to get you to own?",
    [
      "A stealth model",
      "A Knowledge System of Record: sources, policy, methods, provenance, context that survive model swap",
      "More MCP servers",
      "Identic AI as the archive",
    ],
    1,
    "KSOR is the knowledge-work analogue of the transactional system of record.",
  ),
  Q(
    "s34",
    "solo",
    "layer",
    "Windows ODR and Agent Launchers, macOS ACP hosting, Linux shell+files: these are examples of what claim?",
    [
      "The host OS is disappearing so you can ignore it.",
      "Operating systems are growing substrates for discovery, invocation, and containment while still receding as the thing humans click.",
      "Only NVIDIA can host agents.",
      "MCP replaces the kernel.",
    ],
    1,
    "OS as plumbing plus new discovery/containment surfaces.",
  ),
  Q(
    "s35",
    "solo",
    "layer",
    "You give an agent send-on-all-mailers with no threshold. It dispatches a wrong customer notice. The governance miss is?",
    [
      "Not using a stealth model",
      "Over-delegation without permissions, thresholds, audit, and reversible actions",
      "Forgetting P2 schemas",
      "Not naming the worker an identic agent",
    ],
    1,
    "Governance/audit is a layer, not a vibe. Draft-vs-send is the canonical threshold.",
  ),
  Q(
    "s36",
    "solo",
    "agentic",
    "You are choosing between a slash command you always type and a skill you want the model to notice. The decision tree says?",
    [
      "If you invoke it yourself on purpose, command; if it should apply when the task matches, skill.",
      "Skills are Claude-only; commands are OpenCode-only.",
      "Always prefer hooks.",
      "If it reads files, it must be a subagent.",
    ],
    0,
    "Manual repeat → command. Auto expertise → skill.",
  ),
  Q(
    "s37",
    "solo",
    "sdd",
    "Clarify is running as a dump of twenty questions in one message, several of which smuggle implementation. The course’s interview rule is?",
    [
      "One question at a time, no code, until the spec is hard to misread.",
      "As many questions as fit in a single cacheable prefix.",
      "Only yes/no questions about the ORM.",
      "Clarify is performed after build, as a retrospective.",
    ],
    0,
    "Cheap, serial disambiguation. Implementation talk belongs in plan, not Clarify.",
  ),
  Q(
    "s38",
    "solo",
    "thesis",
    "Cherny’s published workflow is called “vanilla”: short shared rules, plan before non-trivial work, a way for the model to verify, many sessions. A junior on your team is collecting prompt packs instead. Where does the agentic-coding ladder say people stall?",
    [
      "Stage 6 parallelize",
      "Between first sessions and “never explain twice” (rules file as a living system), collecting prompts instead of building a system",
      "Stage 0 mindset, which is optional",
      "Beyond this course, which forbids vanilla setups",
    ],
    1,
    "The course says most people stall between stages 1 and 2, hoarding prompts.",
  ),
];
