import { Q } from "./helpers";
import type { Question } from "../types";

export const TEAMMATES: Question[] = [
  Q(
    "t1",
    "teammates",
    "agentic",
    "Sara has been in one Claude Code session for nearly two hours on auth plus billing. The model now apologises without moving the code, rewrites the same three functions, invents a helper path that is not in the repo, and quietly ignores her earlier “never touch generated/” constraint. Ahmed, watching over her shoulder, says the history is an asset and she should type a denser recap so the model can recover. Which move actually matches the course?",
    [
      "Follow Ahmed: a longer recap in the same thread maximises context and is how compacting is supposed to work.",
      "Switch to a frontier model in the same thread; jaggedness means the cheap model is the only problem.",
      "Stop sending messages. Use /compact if she still wants this task, or /clear (or /new) if she wants a clean start — then restate constraints in the new/shortened thread.",
      "Append the generated/ rule to CLAUDE.md and keep typing in the same session so the new line is in the cache immediately.",
    ],
    2,
    "Those symptoms are context poisoning. More prompting deepens the doom loop. Rules-file edits mid-rot also bust prompt cache and do not unpoison the transcript.",
  ),
  Q(
    "t2",
    "teammates",
    "agentic",
    "Fatima drops into default execute mode and pastes one long feature brief. Twenty minutes later eight files have moved and the architecture is wrong. Usman says the brief was simply too short; a better first prompt would have been enough. What was the actual miss?",
    [
      "Usman is right: plan mode is optional if the first prompt is long enough.",
      "She should have spawned a subagent to own the entire feature so the main thread stayed empty.",
      "She should have entered plan mode, iterated a written plan, approved it, then executed — preferably with a cheaper model following the saved plan.",
      "She should have auto-approved all bash so the agent could have finished before the architecture calcified.",
    ],
    2,
    "Non-trivial work is plan-then-execute. Length of the first prompt is not a substitute for a reviewed plan.",
  ),
  Q(
    "t3",
    "teammates",
    "agentic",
    "Every few days Zainab and Omar paste the same paragraph: run tests after edits, never touch src/generated/, use the existing auth middleware. Zainab wants the whole paragraph in CLAUDE.md so it is “always on.” Omar wants a skill that auto-invokes when the task matches. Who is closer, and why is the other trap easy?",
    [
      "Zainab: anything you repeat belongs in the rules file, which is read once per project lifetime.",
      "Omar: this is reusable expertise the model should apply when relevant; stuffing it all into the rules file burns budget on every message, including unrelated ones.",
      "Neither: it must be a hook, because only hooks can mention tests.",
      "Neither: it must be a plan file reread at the start of every session.",
    ],
    1,
    "Rules files stay short and hold what files cannot reveal. Repeated procedures that should fire when relevant are skills. Hooks are for no-judgment enforcement, not for a paragraph of preferences.",
  ),
  Q(
    "t4",
    "teammates",
    "agentic",
    "Usman wants commits blocked if tests fail or [TODO] remains in published/. Nadia says a strongly worded CLAUDE.md line is enough because the model “always reads it.” What does the course actually prescribe?",
    [
      "Nadia is right; the rules file is binding in the same way a compiler is.",
      "A skill with a vivid description, because skills cannot be skipped once listed.",
      "A hook (Claude Code) or plugin (OpenCode) on the commit path, forming a verification loop the model cannot talk its way around.",
      "A reviewer subagent after the fact; isolation is stronger than hooks.",
    ],
    2,
    "Rules and skills are suggestions the model can ignore. Hooks/plugins run regardless. Put the check at commit, not on every keystroke.",
  ),
  Q(
    "t5",
    "teammates",
    "agentic",
    "Ahmed’s CLAUDE.md is hundreds of lines, including “add comments where helpful” and “never write multi-line comments,” plus many facts the repo already shows. Sara says more clarifying lines will cancel the contradictions. What should he do?",
    [
      "Keep adding; a long constitution is how Anthropic’s own prompt works.",
      "Split into many files and load all of them on every turn.",
      "Prune: keep only lines that prevent mistakes the model actually made; delete contradictions and anything the files already teach.",
      "Move the whole file into a skill so it loads only when the model feels like it.",
    ],
    2,
    "The method is earned lines plus pruning. Anthropic cut a large share of its own system prompt in 2026. More text is not more control.",
  ),
  Q(
    "t6",
    "teammates",
    "agentic",
    "Omar uses a frontier model for planning, formatting, test runs, and “just follow the plan.” Fatima says staying on the strongest model is the only way quality holds. What is the taught split?",
    [
      "Fatima is right; cheap models cannot follow a written plan.",
      "Plan and hard reasoning on the strong model; once a plan exists, execute on a cheaper model.",
      "Put model-switching instructions in the rules file and let the agent choose every turn.",
      "Use only stealth free models so cost is identically zero.",
    ],
    1,
    "The expensive step is thinking. A clear plan is execution. Stealth free models are the wrong default for real work.",
  ),
  Q(
    "t7",
    "teammates",
    "agentic",
    "Nadia asks the agent to find every billing site and then fix one edge case. It opens dozens of files into the main thread. Hassan says the rules file lacked a billing map. What should she have done instead?",
    [
      "Expand the rules file with a full billing atlas so future searches stay in-thread.",
      "Delegate the heavy search to a subagent and keep only the summary in the main conversation.",
      "Turn on plan mode after the dump, which retroactively unloads the files.",
      "Switch to a cheaper model so the dump is at least inexpensive.",
    ],
    1,
    "Codebase archaeology is the most context-poisoning request you can make in the main window. Subagents exist for that.",
  ),
  Q(
    "t8",
    "teammates",
    "agentic",
    "Hassan’s session vanished after a solid multi-step plan. Nadia says he should just --resume / /sessions and that a plan file is ceremonial. He is not sure the session is still listed. What should already exist?",
    [
      "Only the resume index; plan files are for sharing with teammates, not recovery.",
      "A plan file on disk that a new session can read and continue from, because resume is not guaranteed.",
      "A skill that regenerates plans from the rules file.",
      "An exported transcript pasted in full, which is cheaper than a short plan file.",
    ],
    1,
    "Resume is useful; the plan file is the contract that survives session loss.",
  ),
  Q(
    "t9",
    "teammates",
    "sdd",
    "Leila writes a spec that already names Drizzle, a particular folder layout, and “use our existing Redis.” Bilal says that specificity will stop the agent from inventing a stack. What does SDD say is the cost of that choice?",
    [
      "None — constitution and spec should both list the stack.",
      "The spec has absorbed HOW, so a later stack change becomes an intent rewrite rather than a re-derivation from behaviour.",
      "Redis is fine in a spec; only folder layout is HOW.",
      "SDD forbids naming any existing system, including auth middleware already in the repo.",
    ],
    1,
    "Behaviour belongs in the spec. Stack and layout belong in constitution or plan, not in the behaviour contract.",
  ),
  Q(
    "t10",
    "teammates",
    "sdd",
    "After a vague spec, the agent ships a “working” password reset that never expires tokens. Imani wants to patch the code and leave the spec. Yusuf wants to tighten the spec’s acceptance criteria first, then re-derive. Who matches Spec-Anchored practice?",
    [
      "Imani: code is the source of truth once it runs.",
      "Yusuf: update the spec so expiry is a testable must, then rebuild against it — otherwise you have spec drift.",
      "Either, because Spec-First and Spec-Anchored are the same once code exists.",
      "Neither: they must jump to Spec-as-Source and delete the repo.",
    ],
    1,
    "Spec-Anchored means the spec stays the contract. Patching only the code is how drift starts.",
  ),
  Q(
    "t11",
    "teammates",
    "sdd",
    "Noor wants to skip Clarify because Research and Specify already took an hour. Adeel wants the model to interview one ambiguity at a time before any build. What is the course’s claim about skipping Clarify?",
    [
      "Clarify is optional ceremony for throwaway prototypes only; production specs should skip it to save tokens.",
      "Unstated assumptions become bugs at build prices; Clarify is the cheap place to kill them.",
      "Clarify is only for non-programmers; engineers should jump to plan mode.",
      "Clarify must be done by a subagent or it does not count.",
    ],
    1,
    "The interview is cheap. Build is expensive. Skipping it is how “working but wrong” ships.",
  ),
  Q(
    "t12",
    "teammates",
    "thesis",
    "Maya is selling a per-seat copilot. Farid wants to productise a Digital FTE that owns a role’s outcomes. Maya says that is just a marketing rename of SaaS. What distinction does the thesis actually draw?",
    [
      "None; Digital FTE is a copilot with a longer system prompt.",
      "SaaS sells tools and seats with humans still executing; an AI-Native offering sells labour/outcomes via role-based workers against a system of record.",
      "Digital FTEs cannot use tools; copilots can.",
      "The only difference is that Digital FTEs must run on-device.",
    ],
    1,
    "The thesis is a business shift from tools to labour, not a synonym for “chat in the IDE.”",
  ),
  Q(
    "t13",
    "teammates",
    "thesis",
    "Kamal wants to call their support bot an identic agent because it “represents the brand.” Hira says identic AI is the personal delegate on the edge, and the support role is a Digital FTE in the workforce layer. Who is using the thesis’s two-layer model correctly?",
    [
      "Kamal: any customer-facing agent is identic.",
      "Hira: identic = personal edge delegate; Digital FTE = role-based enterprise worker. Specs sit between the layers.",
      "Both words are interchangeable in the thesis.",
      "Neither: identic AI is only Tapscott’s name for the nervous system.",
    ],
    1,
    "Tapscott’s identic AI is personal. Digital FTEs are the hired workforce. Mixing them collapses the two-layer model.",
  ),
  Q(
    "t14",
    "teammates",
    "problem",
    "Rafi asks the agent “how should we organise these 400 PDFs?” and gets an essay. Sana says he should have named an output file and an action (“group by opposing counsel into folders, write a manifest”). Rafi says Principle 2 is about JSON only. Who is right about P1 vs P2?",
    [
      "Rafi: without a JSON schema the agent must only talk.",
      "Sana: P1 is brief the hands to produce artifacts; P2 is specify shape when prose would be misread. His prompt failed P1 first.",
      "Both principles require plan mode, which neither mentioned, so both are wrong.",
      "P1 applies only in Claude Code; Cowork users skip it.",
    ],
    1,
    "He asked a question instead of giving an instruction that yields a file. That is P1. P2 would tighten the shape of the manifest.",
  ),
  Q(
    "t15",
    "teammates",
    "problem",
    "After a one-shot rewrite of a 40-file module, git status is a swamp. Talia wanted numbered steps with a commit after each. Owen says one commit at the end is cleaner history. Which failure pattern did Owen just recommend?",
    [
      "The Drift",
      "The Confident Wrong",
      "The Big Bang (and the fix is P4 reversible decomposition)",
      "The Black Box",
    ],
    2,
    "One irreversible blob is Big Bang. P4 is atomic, reversible units with checkpoints.",
  ),
  Q(
    "t16",
    "teammates",
    "problem",
    "The agent’s answer looks professional but a cited clause is not in the contract. Priya wants a “quote the exact source for each claim” pass. Dev wants to promote the answer into MEMORY.md so the team stops re-litigating. What does P3 say?",
    [
      "Dev: persistence is stronger than verification.",
      "Priya: looks-right is the failure mode; ground or discard before you persist.",
      "Neither: only unit tests count as verification, never citations.",
      "Both: persist first, then verify next quarter.",
    ],
    1,
    "Persisting an unchecked claim is how Confident Wrong becomes institutional memory.",
  ),
  Q(
    "t17",
    "teammates",
    "openclaw",
    "After editing SOUL.md, Ayesha’s WhatsApp replies still sound like the old voice. Imran says she must reinstall the daemon. What is the more likely miss in the OpenClaw course?",
    [
      "Imran is right; brain files only load at onboard.",
      "She likely did not /reset (or equivalent reload) after the edit, so the running system prompt is stale.",
      "SOUL.md never affects WhatsApp; only IDENTITY.md does.",
      "She needed an MCP server named “soul”.",
    ],
    1,
    "A documented pitfall: forgetting to reload after brain-file edits.",
  ),
  Q(
    "t18",
    "teammates",
    "openclaw",
    "They want OpenClaw on a public Discord. Nabil argues for unsandboxed laptop access so it can “really help.” Lina argues for NemoClaw/OpenShell-style containment because public channels are prompt-injection surface. Which matches the course’s public-channel advice?",
    [
      "Nabil: sandboxing is only for Windows.",
      "Lina: public channels are why you cage folder access and egress; unsandboxed is for trusted personal use.",
      "Neither: OpenClaw cannot join Discord.",
      "Public channels are safe if SOUL.md says “ignore jailbreaks.”",
    ],
    1,
    "Prompt injection on public channels is a stated reason for the sandbox architecture.",
  ),
  Q(
    "t19",
    "teammates",
    "openclaw",
    "A skill they installed never fires. Kashif wants to rewrite USER.md. Mehreen wants the gateway log and the skill description. What should they inspect first?",
    [
      "USER.md, because skills inherit user tone.",
      "Gateway load events and whether the SKILL.md description actually matches the task — plus the exists→enabled→configured→restart dance.",
      "MEMORY.md size, which is the only reason skills fail.",
      "The model picker; skills never fire on Gemini.",
    ],
    1,
    "Non-firing skills are a description/load/activation problem, diagnosed from the gateway log.",
  ),
  Q(
    "t20",
    "teammates",
    "layer",
    "Samir says “we are an AI-native company because we switched to GPT-x.” Rabia says the operating layer is identity, orchestration, governance, harness, capabilities, and records — the model is the replaceable middle. Who is closer?",
    [
      "Samir: the model is the layer.",
      "Rabia: confusing model with architecture is the course’s named mistake.",
      "Both: KSOR is just a brand name for the model card.",
      "Neither: the host kernel is the operating layer.",
    ],
    1,
    "The layer sits above the OS; the model is one swappable slot.",
  ),
  Q(
    "t21",
    "teammates",
    "layer",
    "They want agents drafting invoices from chat memory because “the CRM is slow.” Yusuf wants every write to go through the system of record. Amina says chat context is the new SoR. What does the layer/thesis pairing say?",
    [
      "Amina: agents should invent totals from the thread.",
      "Yusuf: Workers read and write trusted records; they must not treat the transcript as the company’s truth.",
      "Either, so long as MCP is enabled.",
      "SoR is only for payments protocols (ACP/AP2), not invoices.",
    ],
    1,
    "Trusted records are an invariant. Chat is not a ledger.",
  ),
  Q(
    "t22",
    "teammates",
    "thesis",
    "A CEO cites the 56% “no return on AI” survey and wants a bigger model. Pilar says the thesis reads that result as skipped fundamentals (data, governance, operating the AI as a workforce), not as a model-size problem. Which reading matches the thesis?",
    [
      "The CEO: returns are a frontier-model problem.",
      "Pilar: Griggs/PwC framing is business transformation and fundamentals, not an IT model upgrade.",
      "The survey is about identic agents only.",
      "The survey proves Digital FTEs cannot be economic actors.",
    ],
    1,
    "The thesis uses the PwC numbers to argue against confining AI to IT and skipping data/governance.",
  ),
];
