import { Q } from "./helpers.ts";
import type { Question } from "../types.ts";

export const TEAMMATES: Question[] = [
  Q(
    "t1",
    "teammates",
    "agentic",
    "Sara has been in one Claude Code session for nearly two hours on auth plus billing. The model now apologises without moving the code, rewrites the same three functions, invents a helper path that is not in the repo, and quietly ignores her earlier “never touch generated/” constraint. Ahmed, watching over her shoulder, says the history is an asset and she should type a denser recap so the model can recover. Which move actually matches the course?",
    [
      "Stop sending messages: /compact if she still wants this task, or /clear (or /new) for a clean start, then restate the constraints in the shortened thread.",
      "Append the missing constraint to CLAUDE.md and keep typing, because a rules-file edit made mid-session is picked up immediately by the running session.",
      "Ahmed is right: the history is the asset, so a denser recap in the same thread is how a session that has started to loop is brought back under control.",
      "Neither: the fix is to switch to a stronger model in the same thread, because the looping is a capability limit rather than a context problem.",
    ],
    0,
    "Those symptoms are context poisoning. More prompting deepens the doom loop. Rules-file edits mid-rot also bust prompt cache and do not unpoison the transcript.",
  ),
  Q(
    "t2",
    "teammates",
    "agentic",
    "Fatima drops into default execute mode and pastes one long feature brief. Twenty minutes later eight files have moved and the architecture is wrong. Usman says the brief was simply too short; a better first prompt would have been enough. What was the actual miss?",
    [
      "Usman is right: the brief was too short, and a longer first prompt naming the eight files would have kept the architecture intact.",
      "She should have entered plan mode, iterated a written plan, approved it, then executed — ideally with a cheaper model following the saved plan.",
      "She should have handed the feature to a subagent so that the main thread stayed empty while the architecture was decided off to one side.",
      "She should have auto-approved bash for the duration, because the interruption pattern is what pushed eight files into one unreviewed change.",
    ],
    1,
    "Non-trivial work is plan-then-execute. Length of the first prompt is not a substitute for a reviewed plan.",
  ),
  Q(
    "t3",
    "teammates",
    "agentic",
    "Every few days Zainab and Omar paste the same paragraph: run tests after edits, never touch src/generated/, use the existing auth middleware. Zainab wants the whole paragraph in CLAUDE.md so it is “always on.” Omar wants a skill that auto-invokes when the task matches. Who is closer, and why is the other trap easy?",
    [
      "Neither: it belongs in a plan file that the session rereads at the start of every conversation, which is what plan files are actually for.",
      "Zainab: anything repeated belongs in the rules file, which the model reads once per project and therefore costs nothing to keep verbose.",
      "Omar: this is reusable expertise the model should apply when the task matches, and putting all of it in the rules file taxes every message.",
      "Neither: a hook is the only mechanism that can mention tests at all, so the paragraph belongs on the commit path rather than in either file.",
    ],
    2,
    "Rules files stay short and hold what files cannot reveal. Repeated procedures that should fire when relevant are skills. Hooks are for no-judgment enforcement, not for a paragraph of preferences.",
  ),
  Q(
    "t4",
    "teammates",
    "agentic",
    "Usman wants commits blocked if tests fail or [TODO] remains in published/. Nadia says a strongly worded CLAUDE.md line is enough because the model “always reads it.” What does the course actually prescribe?",
    [
      "A reviewer subagent after the fact, because isolation from the main thread is a stronger guarantee than anything on the commit path.",
      "Nadia: the rules file is read on every message, so a strongly worded line is binding in the same way that a compiler check is binding.",
      "A skill with a vivid description, because a skill that matches the task cannot be skipped once it has been listed in the project.",
      "A hook in Claude Code, or a plugin in OpenCode, on the commit path — a verification loop the model cannot talk its way around.",
    ],
    3,
    "Rules and skills are suggestions the model can ignore. Hooks/plugins run regardless. Put the check at commit, not on every keystroke.",
  ),
  Q(
    "t5",
    "teammates",
    "agentic",
    "Ahmed’s CLAUDE.md is hundreds of lines, including “add comments where helpful” and “never write multi-line comments,” plus many facts the repo already shows. Sara says more clarifying lines will cancel the contradictions. What should he do?",
    [
      "Prune: keep only lines that prevent mistakes the model actually made, and delete contradictions plus anything the files already teach.",
      "Split it into CLAUDE.md and AGENTS.md so each tool reads the half that suits it, since OpenCode prefers AGENTS.md when both exist.",
      "Sara: contradictions cancel out if each is answered by a more specific line, so the file should keep growing until nothing is ambiguous.",
      "Move the file into a skill so it loads only when the task matches, which removes the recurring cost without removing any of the guidance.",
    ],
    0,
    "The method is earned lines plus pruning. Anthropic cut a large share of its own system prompt in 2026. More text is not more control.",
  ),
  Q(
    "t6",
    "teammates",
    "agentic",
    "Omar uses a frontier model for planning, formatting, test runs, and “just follow the plan.” Fatima says staying on the strongest model is the only way quality holds. What is the taught split?",
    [
      "Fatima: quality compounds, so the strongest model should stay in the seat for planning, execution and test runs alike.",
      "Plan and do the hard reasoning on the strong model, then execute the written plan on a cheaper one chosen with /model or /models.",
      "Use the cheapest model throughout and spend the difference on a second review pass by a stronger model once the work is finished.",
      "Match the model per file rather than per phase, so generated code runs cheap while hand-written modules run on the frontier model.",
    ],
    1,
    "The expensive step is thinking. A clear plan is execution. Stealth free models are the wrong default for real work.",
  ),
  Q(
    "t7",
    "teammates",
    "agentic",
    "Nadia asks the agent to find every billing site and then fix one edge case. It opens dozens of files into the main thread. Hassan says the rules file lacked a billing map. What should she have done instead?",
    [
      "Compact first and repeat the search, because a shorter transcript gives the same search more room and therefore fewer files opened.",
      "Hassan: the rules file needed a billing map, and with one the agent would not have had to open dozens of files to find the sites.",
      "Delegate the heavy search to a subagent and keep only its summary in the main conversation, then make the small edit in the main thread.",
      "Split the search across several sessions in parallel worktrees, since each worktree carries its own context window and its own budget.",
    ],
    2,
    "Codebase archaeology is the most context-poisoning request you can make in the main window. Subagents exist for that.",
  ),
  Q(
    "t8",
    "teammates",
    "agentic",
    "Hassan’s session vanished after a solid multi-step plan. Nadia says he should just --resume / /sessions and that a plan file is ceremonial. He is not sure the session is still listed. What should already exist?",
    [
      "A rules-file line recording the plan, since CLAUDE.md is read on every message and therefore survives the loss of a session.",
      "A MEMORY.md entry naming the next step, because committed long-term facts are what carry state between sessions of any tool.",
      "Nadia: resume is the mechanism the tools provide, and a plan file adds ceremony to a session that can simply be reopened.",
      "A plan file on disk that a new session can read and continue from, because resume is a convenience and not a guarantee.",
    ],
    3,
    "Resume is useful; the plan file is the contract that survives session loss.",
  ),
  Q(
    "t9",
    "teammates",
    "sdd",
    "Leila writes a spec that already names Drizzle, a particular folder layout, and “use our existing Redis.” Bilal says that specificity will stop the agent from inventing a stack. What does SDD say is the cost of that choice?",
    [
      "The spec has absorbed HOW, so a later stack change becomes an intent rewrite rather than a re-derivation from behaviour.",
      "Nothing is wrong provided the constitution repeats the same choices, so both documents agree on Drizzle, the layout and Redis.",
      "The cost is only that Clarify becomes shorter, since there is less left to interview about once the implementation has been named.",
      "Bilal: naming the stack is what stops an agent from inventing one, and a spec that leaves the stack open is the riskier document.",
    ],
    0,
    "Behaviour belongs in the spec. Stack and layout belong in constitution or plan, not in the behaviour contract.",
  ),
  Q(
    "t10",
    "teammates",
    "sdd",
    "After a vague spec, the agent ships a “working” password reset that never expires tokens. Imani wants to patch the code and leave the spec. Yusuf wants to tighten the spec’s acceptance criteria first, then re-derive. Who matches Spec-Anchored practice?",
    [
      "Imani: patch the code now and update the spec at the next planning pass, because a broken reset flow is a live defect and the spec is not.",
      "Yusuf: make token expiry a testable must in the spec, then rebuild against it — patching the code alone is how spec drift starts.",
      "Both, in sequence: patch the code, then rewrite the spec from the shipped behaviour so that the document matches what was built.",
      "Neither: expiry belongs in the constitution as a durable constraint, and once it is there the spec needs no acceptance criterion for it.",
    ],
    1,
    "Spec-Anchored means the spec stays the contract. Patching only the code is how drift starts.",
  ),
  Q(
    "t11",
    "teammates",
    "sdd",
    "Noor wants to skip Clarify because Research and Specify already took an hour. Adeel wants the model to interview one ambiguity at a time before any build. What is the course’s claim about skipping Clarify?",
    [
      "Both are wrong: the interview should be run by a subagent, so ambiguities are collected off-thread and summarised into the spec.",
      "Noor: an hour of Research and Specify has already surfaced the ambiguities, so the interview would only restate decisions already taken.",
      "Adeel: unstated assumptions become defects at build prices, and Clarify — one question at a time, no code — is the cheap place to kill them.",
      "Both are wrong: Clarify is a research activity, so it belongs before Specify rather than after it in the four-phase order.",
    ],
    2,
    "The interview is cheap. Build is expensive. Skipping it is how “working but wrong” ships.",
  ),
  Q(
    "t12",
    "teammates",
    "thesis",
    "Maya is selling a per-seat copilot. Farid wants to productise a Digital FTE that owns a role’s outcomes. Maya says that is just a marketing rename of SaaS. What distinction does the thesis actually draw?",
    [
      "The distinction is deployment: seats run in the customer's tenant, while a Digital FTE always runs in the vendor's own infrastructure.",
      "The distinction is model access: a copilot borrows the customer's model budget, while a Digital FTE brings its own inference capacity.",
      "Maya: a Digital FTE is a per-seat copilot with a job title attached, and the thesis describes a pricing change rather than a new thing.",
      "SaaS sells tools and seats with humans still doing the execution; an AI-Native offering sells labour and outcomes through role-based workers.",
    ],
    3,
    "The thesis is a business shift from tools to labour, not a synonym for “chat in the IDE.”",
  ),
  Q(
    "t13",
    "teammates",
    "thesis",
    "Kamal wants to call their support bot an identic agent because it “represents the brand.” Hira says identic AI is the personal delegate on the edge, and the support role is a Digital FTE in the workforce layer. Who is using the thesis’s two-layer model correctly?",
    [
      "Hira: an identic agent is a personal delegate on the edge, while a support role is a role-based worker in the workforce layer.",
      "Both: the support bot is an identic agent while it is in trial, and becomes a Digital FTE once it is given a service-level target.",
      "Neither: a support bot belongs to neither layer, because customer-facing automation predates the two-layer model entirely.",
      "Kamal: a bot that speaks for the brand carries the company's identity and judgment, which is the definition of an identic agent.",
    ],
    0,
    "Tapscott’s identic AI is personal. Digital FTEs are the hired workforce. Mixing them collapses the two-layer model.",
  ),
  Q(
    "t14",
    "teammates",
    "problem",
    "Rafi asks the agent “how should we organise these 400 PDFs?” and gets an essay. Sana says he should have named an output file and an action (“group by opposing counsel into folders, write a manifest”). Rafi says Principle 2 is about JSON only. Who is right about P1 vs P2?",
    [
      "Rafi: P2 is about JSON output, and since no JSON was requested the principle was never engaged; the essay is not a P1 or P2 failure.",
      "Sana: P1 is briefing the hands to produce artifacts, and P2 is specifying the shape when prose would be misread; his prompt failed P1 first.",
      "Both partly: P1 was satisfied because the agent did act, and the essay is a P7 failure because Rafi could not see the reasoning.",
      "Sana, for a different reason: the prompt failed P5, since nothing was written to disk that a later session could pick up and continue.",
    ],
    1,
    "He asked a question instead of giving an instruction that yields a file. That is P1. P2 would tighten the shape of the manifest.",
  ),
  Q(
    "t15",
    "teammates",
    "problem",
    "After a one-shot rewrite of a 40-file module, git status is a swamp. Talia wanted numbered steps with a commit after each. Owen says one commit at the end is cleaner history. Which failure pattern did Owen just recommend?",
    [
      "Scope creep, answered by P6 constraints and an explicit out-of-scope list",
      "Drift, answered by P5 persisting the plan where a later session can find it",
      "The Big Bang, answered by P4 small reversible decomposition with commits",
      "Black Box, answered by P7 observability of every step the agent takes",
    ],
    2,
    "One irreversible blob is Big Bang. P4 is atomic, reversible units with checkpoints.",
  ),
  Q(
    "t16",
    "teammates",
    "problem",
    "The agent’s answer looks professional but a cited clause is not in the contract. Priya wants a “quote the exact source for each claim” pass. Dev wants to promote the answer into MEMORY.md so the team stops re-litigating. What does P3 say?",
    [
      "Neither: the citation should be checked by a stronger model, since a second model reading the contract is an independent verifier.",
      "Both: promote the answer to MEMORY.md with the citations attached, so the memory layer carries the grounding along with the claim.",
      "Dev: once the answer is in MEMORY.md the team stops re-litigating it, and a committed fact is a better record than a citation pass.",
      "Priya: “looks right” is the failure mode, so each claim is grounded against the source or discarded — before anything is persisted.",
    ],
    3,
    "Persisting an unchecked claim is how Confident Wrong becomes institutional memory.",
  ),
  Q(
    "t17",
    "teammates",
    "openclaw",
    "After editing SOUL.md, Ayesha’s WhatsApp replies still sound like the old voice. Imran says she must reinstall the daemon. What is the more likely miss in the OpenClaw course?",
    [
      "She most likely did not /reset after the edit, so the running system prompt is stale and still carries the previous voice.",
      "SOUL.md is the wrong file for voice; tone belongs in IDENTITY.md, which is the brain file the gateway actually loads on startup.",
      "The WhatsApp channel caches the previous persona, so the change appears only once the channel cache expires on its own schedule.",
      "Imran: the daemon must be reinstalled, because brain files are read once at install time and are not re-read by a running gateway.",
    ],
    0,
    "A documented pitfall: forgetting to reload after brain-file edits.",
  ),
  Q(
    "t18",
    "teammates",
    "openclaw",
    "They want OpenClaw on a public Discord. Nabil argues for unsandboxed laptop access so it can “really help.” Lina argues for NemoClaw/OpenShell-style containment because public channels are prompt-injection surface. Which matches the course’s public-channel advice?",
    [
      "Nabil: a personal assistant that cannot reach the laptop cannot really help, and injection is a risk in any channel, public or private.",
      "Lina: a public channel is the reason to cage folder access and egress, while unsandboxed access is for trusted personal use only.",
      "Both, on alternate days: run unsandboxed for members and sandboxed for strangers, since containment is a per-message decision.",
      "Neither: Discord is unsupported for OpenClaw, so the question resolves once the bot is moved to WhatsApp or Telegram instead.",
    ],
    1,
    "Prompt injection on public channels is a stated reason for the sandbox architecture.",
  ),
  Q(
    "t19",
    "teammates",
    "openclaw",
    "A skill they installed never fires. Kashif wants to rewrite USER.md. Mehreen wants the gateway log and the skill description. What should they inspect first?",
    [
      "Kashif, with an addition: rewrite USER.md and MEMORY.md together, since a stale memory layer can suppress a correctly enabled skill.",
      "Kashif: USER.md tells the model who it is talking to, and a skill will not fire until the user profile describes the task it matches.",
      "Mehreen: read the gateway log for load events and check that the SKILL.md description matches the task, then finish the activation dance.",
      "Neither: a skill that never fires is usually an MCP wiring problem, so the connector should be re-added and the gateway restarted.",
    ],
    2,
    "Non-firing skills are a description/load/activation problem, diagnosed from the gateway log.",
  ),
  Q(
    "t20",
    "teammates",
    "layer",
    "Samir says “we are an AI-native company because we switched to GPT-x.” Rabia says the operating layer is identity, orchestration, governance, harness, capabilities, and records — the model is the replaceable middle. Who is closer?",
    [
      "Both: the model is the middle of the stack, and adopting it forces the surrounding layers to appear, so the claim is true in the long run.",
      "Neither: the operating layer is a vendor product rather than an internal structure, so the claim is settled by which platform is licensed.",
      "Samir: the model is the capability, so a company that has adopted the strongest available model has adopted the operating layer with it.",
      "Rabia: confusing the model with the architecture is the course's named mistake; the layer is identity, orchestration, governance, records.",
    ],
    3,
    "The layer sits above the OS; the model is one swappable slot.",
  ),
  Q(
    "t21",
    "teammates",
    "layer",
    "They want agents drafting invoices from chat memory because “the CRM is slow.” Yusuf wants every write to go through the system of record. Amina says chat context is the new SoR. What does the layer/thesis pairing say?",
    [
      "Yusuf: Workers read and write trusted records, and must not treat the transcript as the company's truth when they draft an invoice.",
      "Both: draft from chat for speed, then reconcile against the system of record in a nightly batch so the ledger is eventually correct.",
      "Neither: invoices should be drafted from the knowledge system of record, which holds policy and provenance rather than transactions.",
      "Amina: chat context is the fastest record available, and a Worker that waits on the CRM is a Worker that cannot complete its work.",
    ],
    0,
    "Trusted records are an invariant. Chat is not a ledger.",
  ),
  Q(
    "t22",
    "teammates",
    "thesis",
    "A CEO cites the 56% “no return on AI” survey and wants a bigger model. Pilar says the thesis reads that result as skipped fundamentals (data, governance, operating the AI as a workforce), not as a model-size problem. Which reading matches the thesis?",
    [
      "The CEO: 56% saw no return because the models available at the time were not capable enough, and a stronger model closes the gap.",
      "Pilar: the Griggs and PwC framing is business transformation and skipped fundamentals — data, governance, operating AI as a workforce.",
      "Both: the survey measures IT projects, so a bigger model plus a governance programme is what the thesis is actually recommending.",
      "Neither: the survey measures seat adoption, so the missing 44% is explained by licences that were bought and never used by staff.",
    ],
    1,
    "The thesis uses the PwC numbers to argue against confining AI to IT and skipping data/governance.",
  ),
  Q(
    "t23",
    "teammates",
    "agentic",
    "Hina runs a repository-wide search that dumps several thousand lines of tool output into the chat. Bilal says that is fine and she should simply scroll back and summarise it by hand when she needs it. What does the course actually prescribe for large tool output?",
    [
      "Move the search into a subagent afterwards and ask it to re-read the transcript, which is already a summary of what was searched.",
      "Bilal: a human summary in the thread is itself the verification step, and the raw output stays available for anyone who scrolls back.",
      "Write the output to a file and have the agent report one line, because a large dump in chat busts the cache and poisons the context.",
      "Raise the model's token ceiling so the whole dump fits in context, since truncation is what turns a useful search into a lost one.",
    ],
    2,
    "Big output belongs on disk with a one-line report. Dumping it into the thread costs cache and leaves junk the model keeps re-reading.",
  ),
  Q(
    "t24",
    "teammates",
    "agentic",
    "After a week of clean runs, Rehan wants to auto-approve every bash command so the agent stops interrupting him. Ayesha objects. Which position matches the permissions guidance?",
    [
      "Neither: permissions must always ask, because an approval that has been granted once cannot be reasoned about by the model later.",
      "Neither: permissions belong in the rules file rather than settings, so that the model can read the reasoning behind each denial.",
      "Rehan: a week of clean runs is exactly the earned trust the course describes, so blanket approval is the reward for that record.",
      "Ayesha: auto-approve only the specific actions that have earned it, and keep deny rules for rm -rf, git push and npm publish.",
    ],
    3,
    "Start asking, then widen narrowly. Destructive actions stay denied regardless of track record.",
  ),
  Q(
    "t25",
    "teammates",
    "agentic",
    "Mariam insists the strongest available model should also execute the written plan, because quality compounds over a long build. Daniyal disagrees. Who is closer to the course, and what is the other person's error?",
    [
      "Daniyal: the strong model is for planning, and a cheaper model executes a plan already written — Mariam is paying twice for judgment.",
      "Neither: the model must not change inside a single session, so whichever model wrote the plan is the one that has to execute it.",
      "Neither: execution should be handed to a subagent on any model, since isolation from the main thread is what preserves quality.",
      "Mariam: quality compounds, so the strongest model should carry the build as well as the plan; a cheaper executor is where defects enter.",
    ],
    0,
    "Match the model to the task. Planning is judgment; executing a settled plan is throughput.",
  ),
  Q(
    "t26",
    "teammates",
    "thesis",
    "Kamran proposes buying a chat seat for every employee and reporting the company as AI-Native at the next board meeting. Sadia says that misses the thesis's test. Which test does she mean?",
    [
      "Seat count is the right measure, provided utilisation stays above the threshold the board has set for the reporting period.",
      "An AI-Native company's workforce is mostly AI and its product is whatever that workforce produces; humans hire it for jobs, not seats.",
      "The measure is the share of pull requests written by agents, which is the only figure in the canon that can be audited externally.",
      "The measure is the number of MCP connectors in production, since capability reach is what separates an AI-Native firm from a copilot.",
    ],
    1,
    "Seats are a licence model; the thesis is about who does the work. Cursor's 35%-of-PRs figure is evidence, not the definition.",
  ),
  Q(
    "t27",
    "teammates",
    "thesis",
    "Imran wants the new worker's state split across four specialised stores so each is best of breed. Farah objects on the grounds of the data movement tax. What is her argument?",
    [
      "The tax is paid only at query time, so a read-heavy worker may be split across as many stores as its access pattern can justify.",
      "Specialised stores are always slower, so a single database wins on latency alone and the argument has nothing to do with pipelines.",
      "Every pipeline between stores is a cost the thesis calls a data movement tax, so the default is to consolidate unless there is cause not to.",
      "The thesis forbids more than one datastore inside an AI-Native company, so four specialised stores is a governance violation outright.",
    ],
    2,
    "Consolidation is the default because moving data between stores is the recurring bill, not the storage itself.",
  ),
  Q(
    "t28",
    "teammates",
    "sdd",
    "Halfway through a build the agent has quietly restructured the module layout and dropped two numbered requirements. Zeeshan wants to restart the session with a stronger model. Hira says that misreads the failure. What is her correction?",
    [
      "Neither: the requirements belong in the constitution, where they cannot be dropped by a session that has run for several hours.",
      "Neither: the fix is a hook that blocks commits until the module layout matches the spec, which is a check rather than a restart.",
      "Zeeshan: drift of that size is a capability limit, and a stronger model in a fresh session is the only way to recover the layout.",
      "This is agent drift — re-ground to the numbered requirements — and if code has moved without the spec, that is spec drift to fix too.",
    ],
    3,
    "Two different failures with two different fixes. Restarting loses the re-grounding and leaves the spec behind.",
  ),
  Q(
    "t29",
    "teammates",
    "sdd",
    "Talha wants the full Research → Specify → Clarify → Build loop for a one-line copy change in a footer. Noor objects. What does the course's right-sizing rule say?",
    [
      "Noor: right-size the process — a trivial one-liner can skip the ceremony, while multi-file or architectural work gets the full loop.",
      "Neither: the loop is mandatory for every change, but Clarify may be skipped when the change touches fewer than two files.",
      "Neither: a copy change is a constitution matter rather than a spec matter, so it should be recorded as a durable constraint.",
      "Talha: ceremony is what keeps small changes honest, and a footer string has broken more releases than any architectural decision.",
    ],
    0,
    "The loop is proportional to the risk of getting it wrong, not to the size of the diff.",
  ),
  Q(
    "t30",
    "teammates",
    "problem",
    "Junaid's agent returns a well-written essay describing the migration it would perform, and nothing in the repository has changed. Sana says the brief was wrong rather than the model. What is her reasoning?",
    [
      "The model needed plan mode, which is the only mode in which an agent is permitted to write files into the repository.",
      "P1: brief the hands. Instructions should call for actions that produce artifacts rather than prose about intentions.",
      "The model needed to be told to be less verbose, which is a P7 fix, since the narration was hiding the absence of any change.",
      "The essay should have been written to explore.md, which would have made it an artifact and satisfied the principle on its own.",
    ],
    1,
    "An essay is not an artifact. Writing down what you saw is P5; doing the thing is P1.",
  ),
  Q(
    "t31",
    "teammates",
    "problem",
    "Rabia is content because the agent narrates every step and she can follow the reasoning. Adil says that is not yet a directed system. Which principle is he invoking, and which failure pattern does it answer?",
    [
      "P4 decomposition, answering Drift, because a step-by-step narration is the visible symptom of a task that was never broken down.",
      "P3 verification, answering the Big Bang pattern, because a narrated plan that has not been checked is how large failures land.",
      "P7 observability, answering Black Box — though seeing the reasoning is only the start of directing it, and is not a check on output.",
      "P6 constraints, answering Scope Creep, since an agent that narrates everything is usually an agent that has been given no boundary.",
    ],
    2,
    "Observability answers Black Box. It lets you direct the work; it does not by itself tell you the result is right.",
  ),
  Q(
    "t32",
    "teammates",
    "openclaw",
    "Haris installed a skill two days ago and it has never fired. He wants to reinstall OpenClaw from scratch. Eshaal says the diagnosis is cheaper than that. What does she point at?",
    [
      "The skill must be converted into an MCP tool, because a skill cannot be scheduled and therefore cannot fire on a recurring task.",
      "SOUL.md must name the skill explicitly and the instance must then be reset, since brain files are what the gateway loads at startup.",
      "A skill needs a stronger model before it will activate, so the reinstall would have coincided with a model change and seemed to work.",
      "The description is what makes a skill fire, and the activation sequence ends at configured plus a gateway restart — check both first.",
    ],
    3,
    "A skill that never fires is nearly always a description or activation problem: exists → disabled → enabled → configured, with the gateway restarted.",
  ),
  Q(
    "t33",
    "teammates",
    "openclaw",
    "Zoya wants to attach the family OpenClaw instance directly to a public Discord server so friends can use it. Waleed objects. What is his ground?",
    [
      "A public channel is a prompt-injection surface, so that instance belongs in the NemoClaw sandbox — container, OpenShell prison, guard.",
      "Discord is unsupported, so only WhatsApp and Telegram may be public; the objection disappears once the server is moved.",
      "The gateway port would have to be exposed to the internet, and the licence forbids exposing the dashboard beyond the loopback address.",
      "Public channels are rate limited, so a 429 response is guaranteed within a day and the instance will stop answering altogether.",
    ],
    0,
    "The sandbox exists for exactly this case. An unsandboxed instance on a public channel lets strangers steer it.",
  ),
  Q(
    "t34",
    "teammates",
    "layer",
    "Saad reports to the steering group that the model question is settled and the architecture is therefore done. Amina says the course calls this a category error and adds a second point about reliability. What are her two points?",
    [
      "Saad is right: once the model is fixed, the only architecture left is the prompt, and that is a matter of iteration rather than design — the layers beneath the model are plumbing by definition.",
      "The model is a replaceable generator beneath identity, orchestration, governance and capabilities; and since reliability is not 100%, governance and hybrid review are part of the design.",
      "The architecture is the harness, and reliability is a matter of retries; once the control plane re-runs any step that failed, human review becomes redundant rather than merely expensive.",
      "Governance is a legal concern rather than an engineering one, so the steering group is entitled to treat it as out of scope for the architecture and revisit it at the next audit.",
    ],
    1,
    "Model is not agent is not layer, and agents fail often enough that the layer has to catch it.",
  ),
];
